### ISSUE TITLE
Markup in search results

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#104]
The search results include format elements like ``====`` , `` .. note::`` or ``*``. Example:

```
Writing a Plugin
================ Writing a Plugin ================ .. tip:: Read 
:doc:`../../workspace/index` to prepare your workspace for plugin development! 
.. note:: The instructions within the Sponge Documentation assume that you have prio...
```
I think the search results should be unformatted plain text.

**Comment by gratimax** [comment]
Unfixable without major changes in how sphinx works. You are welcome to try.
