### ISSUE TITLE
Improve command class example

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#109]
The command class example (``plugins/commands.rst``) should be improved.

According to the ``CommandCallable`` javadoc, the usage String should only be ``"<message>"``.

The permission string should be something like ``"example.broadcast"``.

Also, some comments explaining the fields and methods (especially ``call``, ``testPermission`` and ``getSuggestions``) would be great.

**Comment by gratimax** [comment]
Please make a PR with suggested improvements

**Comment by boformer** [comment]
#117

**Comment by BlackGoat** [comment]
Did this ever get resolved? (Just cleaning up here)

**Comment by boformer** [comment]
No, the issue is not resolved.

We now have 2 command APIs: The old API that was slightly changed (``CommandCallable``, ``Dispatcher``) and the new API with argument parsing (``CommandSpec``, ``CommandElement``).

We need a documentation for both APIs.

**Comment by BlackGoat** [comment]
Then it is as I had feared. The Commands API (part I and II) is still lacking sufficient explanation. Calling for volunteers to get this done!
