### ISSUE TITLE
How do we want the changelog page to work?

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#11]
When we *have* a changelog for Sponge, we'll need a way of making it available to SpongeDocs.
Options: (1) Link to another page, eg. a Jenkins changelog (2) uploading each file to Docs (preferably automated) and adding to index. Anyone else got any bright ideas, or preferences?

**Comment by Inscrutable** [comment]
Changelogs are now automatically generated and presented on the respective Downloads sites:
[SpongeForge](https://repo.spongepowered.org/maven/org/spongepowered/sponge/) | [SpongeVanilla](https://repo.spongepowered.org/maven/org/spongepowered/spongevanilla/) | [SpongeAPI](https://repo.spongepowered.org/maven/org/spongepowered/spongeapi/). We need to remove the Docs Changelog page altogether, and mention the changelog on the Downloads page.

**Comment by boformer** [comment]
Does this really replace a readable change log?

It is hard to find the differences between 2 major versions, and to identify which changes are important.
