### ISSUE TITLE
Make navigation easier

### ISSUE THREAD

**Issue by Brycey92** [SpongePowered/SpongeDocs#115]
I propose some indicator, on the left-hand menu, to let people know that there are additional pages under a category. A tree could even be implemented so users can manually expand and hide categories within the menu.

**Comment by gratimax** [comment]
I am not going to do this, but you are free to try since it's an okay idea.

**Comment by Tzky** [comment]
I thougt about this as i like the current menu but feel that there could be improvements. 
This is what i came up with (small buttons on the menu to collapse/expand submenus) :

![menutest2](https://cloud.githubusercontent.com/assets/10940670/6428567/a4f77c9e-bfa7-11e4-8c83-4df0086e3719.png)

**Comment by tyrannokapi** [comment]
I may work on this, though I've been a bit busy lately. It's only a few lines of jQuery.

**Comment by BlackGoat** [comment]
Issue moved to sponge_docs_theme. Closed here for now.
