### ISSUE TITLE
[Feature] Propose Changes button

### ISSUE THREAD

**Issue by Brycey92** [SpongePowered/SpongeDocs#116]
Most modern wiki sites have some functionality where users can edit a page or propose changes for review. This may be more difficult for this wiki, since it is connected to a GitHub repo, but I'm relatively new to git, so it could be easier than I think.

**Comment by simon816** [comment]
That's what GitHub Pull Requests and Issues are for

**Comment by gratimax** [comment]
@simon816 he means on the site itself

**Comment by gratimax** [comment]
I was looking into this already. Will most likely fix soon

**Comment by BlackGoat** [comment]
Issue moved to sponge_docs_theme. Closed here for now.
