### ISSUE TITLE
Odd wording in users/index.rst

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeDocs#119]
The second sentence on the index page for the User's Guide reads (emphasis added):

**In this guide is a number of pages discussing topics *useful* that a server owner can find useful.**

The first *useful* doesn't make sense, and should be removed. The sentence would then read as follows:

**In this guide is a number of pages discussing topics that a server owner can find useful.**

**Comment by gratimax** [comment]
??? @BlackGoat explan?

**Comment by Minecrell** [comment]
@gratimax  https://github.com/SpongePowered/SpongeDocs/commit/875c1b210acb2254f0e192d00f1fa12b0e851165 probably

**Comment by BlackGoat** [comment]
Yeah, just a quick fix. Sorry if I didn't leave a ref to the commit.
