### ISSUE TITLE
No mention of Guice or Guava?

### ISSUE THREAD

**Issue by Xemiru** [SpongePowered/SpongeDocs#123]
I've noticed we lack any mention of those two libraries being used in Sponge. Considering we use them extensively in the API, they'll probably need those two to be able to develop their plugins. There are references to parts of the library, e.g. the **@Inject** annotation in some examples, and importing things from Google commons, but to a new developer this might be assumed to be included with the API.

**Comment by boformer** [comment]
That's especially important for people who are not working with maven or gradle.

**Comment by boformer** [comment]
Related to https://github.com/SpongePowered/SpongeDocs/issues/67

**Comment by gratimax** [comment]
Closing in favor of #67

**Comment by Xemiru** [comment]
Noting that Guava's Optional<T>s aren't part of injection, as far as I'm concerned.

**Comment by gratimax** [comment]
True. I would split that out into a separate issue
