### ISSUE TITLE
Translation of new external reference links

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#126]
The last PRs introduced a centralized list of all links at the top of each .rst. While this makes the sources look tidy and neat, it introduces a problem for the translators:
If the references are translated the links will obviously break. As Crowdin does not provide the link list, translation of both (links + reference at the top and reference in the text) isn't an option.

Currently there's only the option to leave the references untouched which results in: 
[translated text]... english linkname ...[translated text], which is very unpleasant.

For me there are two possible solutions:
-revert the change and link as before
-convince sphinx (or the *.po parser) to include the link list to allow for translation of both

**Comment by boformer** [comment]
I would say revert.

**Comment by Tzky** [comment]
Would be my choice too. Forgot to ping @Xemiru as he introduced this.

**Comment by simon816** [comment]
Is there a way to use keys as the URL identifier, then inline the translated text with the key?
For example, (Note: I am making the syntax up)
\`example\` = example.com

See the {\`example\`}
Voir {\`example\` l'exemple} (Thanks Google Translate)

**Comment by boformer** [comment]
@simon816 We could use anonymous hyperlinks:

```
See the  `Sponge Project Homepage`__.
The `source of the Sponge API `__ is available on GitHub.

.. __: http://www.spongepowered.org
.. __: http://www.github.com/spongepowered/spongeapi
```

I don't think that it is better than inline links. When you change the order of the anonymous links in the text, you always have to resort the link list.

See http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets

**Comment by tyrannokapi** [comment]
I'd have to agree on reverting this change. The centralized list of links may be convenient, but ease of maintainability has to be considered.

**Comment by Xemiru** [comment]
mmh, translations would have to take priority over the reference organization. anonymous links aren't that great either but it would still support having a centralized list of links; i don't expect much to change in terms of the order of links since they almost always seem to be sparse around the page.

with the choice for anon links or in-line links, they both support translatability. willing to try organizing for anonymous links, though, considering above.

**Comment by BlackGoat** [comment]
The law of unintended consequences strikes. This was originally intended to help deal with a plethora of javadocs links, but #127 may be a better solution. Unless we can restore translation of the link text, this has to be reverted. Any more comments?
