### ISSUE TITLE
Implement a way of adding javadoc links without hard-coding the URL

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeDocs#127]
Currently, the only semi-official javadoc homepage is marked as "temporary link", yet occasionally it is important for the documentation to provide a link to a certain javadoc.

The preferred way to do so would be a custom rst role like
```
for details about how Sponge will soak up FLARD see :javadoc:`org.spongepowered.api.soaker.FLARDSoaker`
```
or
```
the first step to not being seen is to call the :javadoc:`hiding.Nesbit#setNotStandingUp` method
```

Thoughts:
 * default link text is the name of the class / method referenced
 * base url for javadocs is configured while building the docs
 * no more hard-coded javadoc links in the documentation

According to http://sphinx-doc.org/extensions.html#where-to-put-your-own-extensions it is possible to provide project-local sphinx extensions. I think that may be a legit way to solve this. 
There is also a built-in extension to include external links to source code which maybe can be abused to achieve this: http://sphinx-doc.org/ext/linkcode.html

**Comment by boformer** [comment]
Sounds good.

**Comment by BlackGoat** [comment]
This may be relevant: http://bronto.github.io/javasphinx/

**Comment by Tzky** [comment]
I think a better solution for this issue would be either:
- using custom roles (like 'javadocs':`link here`
or
- using a Sphinx extension (like https://github.com/bluekeyes/sphinx-javalink)

The former is a good step in the right direction and doesn't need any custom modules/extensions for Sphnix. The latter seems to be the best possible solution, but requires a 3rd party extension.

**Comment by ryantheleach** [comment]
@Tzky You tried doing this previously, but how is it standing at the moment? What's the current way to link to the javadoc methods?

**Comment by Tzky** [comment]
we're currently hardlinking via regular HTML links aka the manual way

**Comment by ryantheleach** [comment]
I couldn't get javasphinx to install locally on windoofs using pip. it has dependencies that need to be built using tools not available on windows, something to do with libxml2
