### ISSUE TITLE
Fix Build

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeDocs#130]
Currently building the docs using grunt or make fails, because the theme resides in the spongedocs-theme folder but the build scripts are looking for sponge-theme.

**Comment by gratimax** [comment]
You need install dependencies and run `gulp build` in the theme directory, then copy over the build/ directory from the theme directory into 'sponge-theme'. I understand that this process is rather difficult to perform, and it will be changed once I distribute the theme through pip.
