### ISSUE TITLE
Mention default data of permission service

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#136]
This is quite important for Bukkit plugin ports, and also useful for other plugins.
- Create permissions that are true by default
- Disable implicit inheritance

https://github.com/SpongePowered/SpongeAPI/issues/494#issuecomment-78165659

**Comment by BlackGoat** [comment]
Thus far, Issue #32 (writing about the Permissions API) hasn't had any contributions. The stub page is at source/plugins/permissions.rst for reference. This explanation would belong there too.

**Comment by Inscrutable** [comment]
Bumping this because it could really use some attention.
@zml2008 will you be able to help us get this out of the way?

**Comment by zml2008** [comment]
Not right away -- also there are a few changes to the permissions API coming in in v5 (regarding default data specifically) that would be useful to incorporate.

**Comment by ST-DDT** [comment]
Is this covered by: https://github.com/SpongePowered/SpongeDocs/pull/536
Or is there anything missing for that?
