### ISSUE TITLE
Event-Bus: Firing Events etc - text needed

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#14]
The page source/plugins/event-bus has some text (from sk89q), but the part on Firing Events and below is blank. Would some kind and knowledgeable soul please fill these parts in, or re-write this doc?

**Comment by BlackGoat** [comment]
PR#53 fixes this, thanks @boformer. It ends on Callbacks, would that have enough content that justify it's own page? (It is quite long already).

**Comment by boformer** [comment]
No idea, I don't understand callbacks ;)
