### ISSUE TITLE
Items API elaboration requested

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#141]
Sponge now has an Items API https://github.com/SpongePowered/SpongeAPI/pull/495 thanks to @gabizou . There is much in the initial PR description that can be reworded for SpongeDocs, by someone with a better grasp of the API and Java than I. Would anyone like to volunteer?

**Comment by jacklin213** [comment]
Hmm where would a file explain this go though?

**Comment by BlackGoat** [comment]
The docs are about to have a restructure (#133), after that it would belong in source/plugin/basics/ as a new file called Items.rst. Hold off until that PR is through, then go for it.

**Comment by BlackGoat** [comment]
There is a new [Data API](https://github.com/SpongePowered/SpongeAPI/pull/542) that subsumes parts of this. We may need to reconsider how these pages are structured, in light of the common data structure now established.

**Comment by sam4215** [comment]
Dibs on this page, feel free to assign this issue to me.

**Comment by BlackGoat** [comment]
Go crazy. Try to co-ordinate with @gabizou who is due to give us docs on the Data API (eventually).

**Comment by 12AwsomeMan34** [comment]
Is this issue still needed?

**Comment by gabizou** [comment]
I do believe so, there's a lot about using Data API, like the properties for items and the data for items.

**Comment by ryantheleach** [comment]
Should mention how to create an itemstack from scratch, from blocks, as well as spawning item entities in the world from represented item stacks.

**Comment by gabizou** [comment]
Especially encouraging the use of `ItemStack.builder()` since I've seen a few people still getting the game registry and getting the builder through that.
