### ISSUE TITLE
Migration pages need some love

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#144]
The "Migrating to Sponge" pages should be extended:

* How to migrate plugins + plugin configs
  * Mention Pore
* Migrate worlds
* Migrate Ban list and similar files

A "Migrating from Vanilla MC" would also be a nice addition.

https://docs.spongepowered.org/en/server/getting-started/migrating/index.html

**Comment by modwizcode** [comment]
I was under the impression pore was not being mentioned in the docs because it's not an official project, and people might think it was if we put it in the docs.

**Comment by Tzky** [comment]
As Pore merged with LapisBlue it might be best to include LapisBlue instead?!

**Comment by modwizcode** [comment]
LapisBlue is a team not a project iirc.

**Comment by tyrannokapi** [comment]
I intended to do this a while back, but it slipped my mind. In particular, I think we need to explain how to correct the world structure, as CraftBukkit relocated the overworld, nether, and end. On that note, I would love for a someone to verify how Sponge handles worlds (if different than vanilla).

I'm unsure if we should include how to migrate plugin configurations. While it could be done manually, the risk for user error is huge - and there's no guarantees that plugins migrated to Sponge will even retain the same configuration structure as their counterparts on the other platforms. I am of the opinion that we should just include a note saying that plugin developers may or may not automatically convert configuration files. Including instructions on how to migrate plugin configuration just assumes a bit too much.

As for Pore: as much as it would help people, I don't feel as if it belongs in SpongeDocs at the current moment. It's a bit out of the scope of the docs, plus it appears they are writing their own documentation. If anything, we could just link to their docs with the mention that it is not an official Sponge project.

A vanilla migration page is likely needed, yes. I think it'll end up being a bit of a stub article, so perhaps we need a picture of vanilla ice cream on it. :stuck_out_tongue:
