### ISSUE TITLE
Redundant .po files in Crowdin

### ISSUE THREAD

**Issue by Dannyps** [SpongePowered/SpongeDocs#150]
The PR #133 deleted some .po files from GitHub. However, those files weren't deleted from Crowdin, where they're still available for translating. If a language wasn't fully translated before this PR, a translator might be translating old strings in vain. In the meantime, I've developed a [user script](http://danielsilva.tk/repo/js/crowdin.beta.user.js) that warns the user not to translate a file if it doesn't exist in the docs. However, this is clearly a lousy solution. There should be a way of removing old files from Crowdin, right?

**Comment by Tzky** [comment]
#96 might be relevant.

**Comment by Dannyps** [comment]
I know it's possible to remove any file from Crowdin. It's a quite simple process.

**Comment by gratimax** [comment]
The crowdin cli simply doesn't delete files. Either we would need to delete the files manually (eww) or write a script to delete it for us (even more eww). Perhaps if I refactor the many bash scripts in etc/ I'll get to doing something like this using the crowdin API directly, but for now it's unlikely I'll get time to fix this issue.

**Comment by Dannyps** [comment]
"write a script to delete it for us"

I haven't written a script that does this, but I wrote a similar one:

The user script I wrote makes an HTTP request to the SpongeDocs website and, if the HTTP code isn't 200, the script signals that that page is not to be translated. There are certainly easier ways of doing this, but it's a way of thinking that may help.

**Comment by gratimax** [comment]
There's an API endpoint available on crowdin to A) list all files and B) delete files. Something that would do this automatically would:

1. Get the file list
2. For each .po file, check if it exists 
3. If it does not exist, make an API request to delete

**Comment by BlackGoat** [comment]
For translation purposes, do we need to keep the old files for reference? The real problem is flagging unused pages for translators so they don't waste their time. If there's no better solution on the horizon than a user script, I should close this issue.

**Comment by Dannyps** [comment]
I looks like those files have been deleted. Thus, this is no longer a problem, for the time being.

**Comment by BlackGoat** [comment]
Thanks, I'll close this for now. Redundant files don't crop up very often, so manual review may be the best solution anyway.

**Comment by Piratdu52** [comment]
source/server/getting-started/implementations/granite.rst is no longer used.

**Comment by Dannyps** [comment]
The file **/source/server/getting-started/installation.rst** is still available on Crowdin, even though it has been deleted.

**Comment by Tzky** [comment]
Thanks for reporting this one. I hid the strings of ``/source/server/getting-started/installation.rst``

**Comment by Dannyps** [comment]
I've noticed. Thanks :smile:

**Comment by ryantheleach** [comment]
That script seems interesting, the only thing I would be scared of is intermittent issues causing non 200 responses and pages disapearing from crowdin.
