### ISSUE TITLE
Video Tutorial for plugin creation

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#157]
It would be nice to have an "official" video tutorial that is embedded in the doc page.
There can be multiple versions for different languages (and maybe different OS/IDEs).

I'm suggesting this because there are so many (bad) tutorials on youtube. It is easier to follow the steps when the documentation is right below the video.

I would also suggest a video that explains the advanced setup that is described here: https://github.com/SpongePowered/SpongeDocs/issues/85

**Comment by modwizcode** [comment]
I would like to make some videos, I will have to plan them out though, also they will rely on the API for the features I discuss being fully completed. But I can start with a series of "Explain Sponge's API for doing XYZ" before working on tutorials that might need more fleshed out API's to complete full featured plugins.

**Comment by boformer** [comment]
A "How to setup a server" video would also be nice.

**Comment by BlackGoat** [comment]
Mumfrey has made a [short video on setting up Sponge in Eclipse](https://www.youtube.com/watch?v=6d42wDHbAfE). It might be useful here.

**Comment by AnUnknownMiner** [comment]
While that video will help, there should be a video on how to setup a actual server that's not in a development environment once Sponge has a stable/usable release.

**Comment by ryantheleach** [comment]
That video also shows how to set up *sponge* development, not sponge plugin development, whilst useful it doesn't fulfil this issue.

**Comment by BlackGoat** [comment]
How about [this](https://forums.spongepowered.org/t/a-collection-of-how-to-videos-for-sponge-development/6992)? I think these are good enough to link in the Docs.

**Comment by Inscrutable** [comment]
Sibomots gave us ten tutorial videos. I think we can close this issue now.
