### ISSUE TITLE
Data and Persistence API - please explain

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#164]
The new Data API supersedes some of the older persistence API. USe of the new features needs to be explained on the docs by someone who knows how it all works. I haven't the foggiest idea.

**Comment by gabizou** [comment]
It works by *FLARD* magic.

**Comment by ryantheleach** [comment]
- [ ] Explain how to get builders.
- [ ] Clone / get data from an existing DataHolder.
- [ ] Get default values for a DataManipulator.
- [ ] Explain optionals, and under what circumstances a DataManipulator may not be available
- [ ] Explain Properties, types, and how they differ from DataManipulators.
- [ ] How to translate from one Type to another(possible?)
- [ ] Serializing. To be specific, going from configs, to NBT, to SQL / custom type to JSON?.
- [ ] Creating your own Properties/DataManipulators/Types attach custom data, make it serializable, how to instantiate it back from it's serialized form.
- [ ] Create your own serializer / dataholder. Allow people to attach data to your own objects, or serialize out to a network connection or something custom. Maybe use a cross server mail plugin, or auction house as an example, or saving player inventories out to an external service.

**Comment by boformer** [comment]
This is really important. This also applies to me:

> I haven't the foggiest idea.

**Comment by saladoc** [comment]
SpongePowered/SpongeAPI#705 will definitly have a great impact on his once accepted.

**Comment by BlackGoat** [comment]
API#705 has now become the great literary work known as https://github.com/SpongePowered/SpongeAPI/pull/685 which might be adapted for the Docs. Here is my humble interpretation:
"something something Data API,
something else the end kthxbai"

**Comment by saladoc** [comment]
Since #331 included the first explanations for the data api, I'll close this in favor of #335
