### ISSUE TITLE
Sponge-specific permissions

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeDocs#166]
Since sponge defines a few of its own permissions, it's probably good to have them in the docs.

## Minecraft ##

- `minecraft.command.<command>`: Give permission to use a certain minecraft command
- `minecraft.commandblock.edit.block.<name>`: Allow editing a block commandblock of the given name
- `minecraft.commandblock.edit.minecart.<name>`: Allow editing a minecart commandblock of the given name

## Sponge ##
(These commands may require additional arguments)

- `sponge.command.chunks`: /sponge chunks
- `sponge.command.config`: /sponge config
- `sponge.command.reload`: /sponge reload
- `sponge.command.save`: /sponge save
- `sponge.command.heap`: /sponge heap
- `sponge.command.version`: /sponge version
- `sponge.command.audit`: /sponge audit

**Comment by BlackGoat** [comment]
OK, theer is a page for Sponge commands at server/spongineer/commands that could use some of this info. Creating a related permissions page may be useful too, as not all permissions necessarily have a related command.
