### ISSUE TITLE
SpongeCommon pages

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#167]
With the division of Sponge into Sponge (coremod) + SpongeCommon, we to add need a new section describing contributing SpongeCommon. Pages that need changing:
- contributing/index.
- new section needed in contributing for SpongeCommon

**Comment by gabizou** [comment]
I feel that adding on to this, we should explain the specific uses for each of the projects. To summarize what I would imagine going as a description for each:

*SpongeCommon*: The core of both official implementations of the SpongeAPI. Here resides all core services and the "common" layer of implementation that is usable between both Sponge and SpongeVanilla. Almost all implementation should reside here with separation of interfaces as necessary for special handling per implementation.

*Sponge*: The forge implementation extending SpongeCommon with special handling for maximizing compatibility with Forge, and therefor potentially hundreds of forge mods.

*SpongeVanilla*: The vanilla implementation acting as a standalone implementation having complete control over the Minecraft Server, this implementation will have little support for custom mods wishing to add new things like blocks, items, etc.

Of course, this is just off the top of my head, but it would be wise to explain *why* we have the three repos and what purpose they serve, aiding potential contributors to understand what exactly they should be aiming to target with regards to helping write implementation.

**Comment by BlackGoat** [comment]
True, the *purpose* of the triumvirate may need explaining somewhere (either in contributing/index, or somewhere in about-sponge). But from most users perspective, it's irrelevant - unless you're *contributing* to them.

**Comment by gabizou** [comment]
> unless you're contributing to them.

Which is mostly what people will want to be able to read on the docs, regardless whether they're server owners (consumers) or developers (well... developers).

**Comment by Tzky** [comment]
#168 might be related as complete refactoring of /contributing might be needed.
