### ISSUE TITLE
Merge Sponge and SpongeVanilla/Mixins

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#168]
At the moment they both have exactly the same content.

It would be better if this were merged together where possible and maybe included on both pages?

Edit: The instructions on using git are in the same boat.

**Comment by Tzky** [comment]
This is right. I added the Vanilla page to allow for new content. In the future there might be differences between Vanilla and the coremod.

Merging both into one Page + seperate Sections for the differences of Vanilla and Coremod might be best.

**Comment by BlackGoat** [comment]
Admittedly, the mixin page need not be duplicated, but linked to each page set instead. This section could still use some rearrangement and/or optimisation.

**Comment by Tzky** [comment]
Not only the mixins page could be refactored (again...). The complete contributing section should get sorted out. I'm thinking of merging Sponge and SpongeVanilla (as they're almost the same) and add SpongeCommon.

This would leave us with this:
* SpongeCommon
    * Layout of...
* Sponge and SpongeVanilla
    * Mixins
    * Debugging within the IDE
    * Git workflow
    * Layout of...
* SpongeDocs
    * Git workflow
    * Layout of...
* SpongeAPI
    * Git workflow
    * Layout of...

**Comment by BlackGoat** [comment]
Mixins should be common to both Sponge (coremod) and SpongeVanilla, so I thought maybe it might belong in SpongeCommon instead. I'm not sure debugging in IDE or Layout will be the same for the two implementations, so they might still need separate pages.

**Comment by BlackGoat** [comment]
Admittedly, I have little idea what the Layout pages or Debugging pages are intended to contain. Let's not make any more of these empty placeholders in this section until we have some content for them.

**Comment by Tzky** [comment]
A small update on this:
I merged the three mixin pages by including common/mixins.rst into the other 2 in PR #188.
