### ISSUE TITLE
SpongePowered/CookBook

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#169]
I suggest that any code snippets in the Docs, should be available in the CookBook.

It allows us to check whether the code compiles, and when the docs have faded out of date compared to the current API.

Is there any way to include code straight from a project into the docs? Isn't that what Sphinx is all about?

I'd also love to be able to reference a method, and either get a link, or mouse highlight, or some sort of embedded javadocs when referencing SpongeAPI methods or Classes.

**Comment by boformer** [comment]
The CookBook contains complete example plugins. It would be great if we had example plugins for every part of the API.

**Comment by ryantheleach** [comment]
I'm guessing theres no way to abuse code coverage tools to check to see if we actually do have plugins that use the entire API?

**Comment by BlackGoat** [comment]
Cookbook has a slightly different intent: it's supposed to contain complete (demo) plugins. Code snippets are outside of the scope of Cookbook. Small code examples in SpongeDocs are acceptable, but it isn't intended to hold entire plugins, nor be live-updated. Sorry.

**Comment by ryantheleach** [comment]
Ok. I just thought it would be invaluable if it were somehow possible to validate that the code snippets could be compilable, at least while sponge is still in flux.
