### ISSUE TITLE
Tell users that the built in minecraft GUI has been disabled.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#171]

**Comment by boformer** [comment]
I don't get this.

**Comment by Deamon5550** [comment]
@boformer we disabled the default server gui as it is ridiculously intensive and rather useless

**Comment by BlackGoat** [comment]
The built-in GUI *does* give a crude tick-length (reciprocal TPS) and memory use, which is something that the standard Java console does not provide. If the GUI's been nerfed, I guess we have to describe it as a "feature" in Sponge and SpongeVanilla (assuming it will affect both).

**Comment by ryantheleach** [comment]
I'd be more interested in if we can add an ascii toolbar to the console with the TPS and Memory use, and currently online player count.

**Comment by Tzky** [comment]
The request for an ascii based console output should be placed in Sponge, SpongeVanilla or SpongeCommon.

**Comment by boformer** [comment]
@ryantheleach Wouldn't that remove the ability to scroll in the console window?

**Comment by zml2008** [comment]
just gotta capture mouse events and deal with them
