### ISSUE TITLE
Highlight doesn't show which mode it's in

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeDocs#178]
I'd prefer it if the highlight button actually toggled (or something visual aid thing) when pressed, instead of just remaining the same. It would show the current state much better than having to find a code snippet + scroll to top + hit button.

**Comment by BlackGoat** [comment]
You mean the "highlight code Light/Dark" button on the top right? It would be nice if it darkened when the code background was dark, but it's not exactly high priority. I think @gratimax might be able to fix this.

**Comment by boformer** [comment]
I don't understand why the button is needed at all.

**Comment by gratimax** [comment]
@boformer Hey, not like I spent any work on it...

I will add a toggle indicator when I get more time, probably when the theme will be tweaked in preparation for the site unification.

**Comment by BlackGoat** [comment]
Issue moved to sponge_docs_theme. Closed here for now.
