### ISSUE TITLE
sponge.readthedocs.org Out of date.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#179]
Can we either update it or nuke it, otherwise it will cause confusion if anyone ever finds it.

**Comment by BlackGoat** [comment]
I hadn't realised this was still available. @gratimax can we archive or nuke this?

**Comment by gratimax** [comment]
This isn't an issue. We don't link to read the docs, and the first hit to [sponge documentation](https://www.google.com/search?q=sponge%20documentation1) is the new documentation.

**Comment by ryantheleach** [comment]
People may have remembered where it was however, I'd still like to see this issue kept open until the problem is dealt with, even if it is minor.

**Comment by RobertHerhold** [comment]
I'd also like to note that it's the 5th link on that google search, so people still might see it (although somewhat unlikely)
