### ISSUE TITLE
Update Staff page

### ISSUE THREAD

**Issue by DotDashh** [SpongePowered/SpongeDocs#181]
A couple of people have been added to the Sponge staff (such as FerusGrim), and the docs should be updated to represent that.

**Comment by BlackGoat** [comment]
FerusGrim was only just promoted. Who else is missing from the list?

**Comment by gabizou** [comment]
@Deamon5550 needs to be added as a CoreDeveloper.

**Comment by BlackGoat** [comment]
I just did all that to test the new Spongie bot. Anything else, or shall I close this?

**Comment by Tzky** [comment]
Time to dig this up again. As Inscrutable dragooned more people into working on the docs the staff page has to get updated _again_
