### ISSUE TITLE
Log examples and explanation needed

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#19]
The page source/users/logs needs some Forge specifics (file-naming, logging conventions) and preferably a log example from a clean Forge 1.8.X server (and/or links to relevant Forge Wiki pages). This is aimed at server admins. Low hanging fruit, any volunteers?

**Comment by BlackGoat** [comment]
With SpongeVanilla in the mix, the logs are going to look different. This stuff is useful for helping users isolate problems and report issues, so some basics would be useful. Or we just drop the page...

**Comment by Inscrutable** [comment]
The idea is to teach new users how to find useful info about crashes / problems, and locate the important / relevant log files. This *could* save devs a degree of hassle.

1. How to fing log files (SpongeForge vs SpongeVanilla)
2. How to read them (where to find sponge version, forge version, mods lists, plugins init, warnings, how to find what went wrong etc).
3. How to share them (pastebin links etc)

Possibly also some info on enabling verbose logging, if available.
The page is *NOT* for collecting common errors, plugin incompatilibities, or other lists.

**Comment by Tzky** [comment]
#350 is merged, we might consider more logging/debug examples in the future.
