### ISSUE TITLE
JavaDocs Link.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#198]
Mention the JavaDocs, and link to it somewhere in the documentation, probably under plugin development, or how to seek help.

Is this the correct link? http://spongepowered.github.io/SpongeAPI/

**Comment by simon816** [comment]
It's a temporary link; but like the sponge logo, seems that temporary is more like semi-permanent :)

**Comment by BlackGoat** [comment]
Definitely an idea I support. The appropriate places to add a link to the Javadocs are:
* plugins/index (almost done - just turn bold JavaDocs into link)
* contributing/api/index
* contributing/index
We don't have much in the Docs on how to seek help in the development process. That might be worth looking into as a separate issue, both for plugins and contributing.

**Comment by Tzky** [comment]
I'd suggest using http://javadocs.spongepowered.org and link that to http://spongepowered.github.io/SpongeAPI/

This way the link can easily be changed without worrying about the docs.
