### ISSUE TITLE
Issue with bullet list on commands page

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#200]
The list is not parsed correctly:
http://docs.spongepowered.org/en/plugin/basics/commands.html#child-commands

**Comment by BlackGoat** [comment]
"Nested lists are possible, but be aware that they must be separated from the parent list items by blank lines" - from the Sphinx ReST docs http://sphinx-doc.org/rest.html?highlight=bullet. Fixxored.
