### ISSUE TITLE
Fill 'Argument Parsing' page

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#201]
- [ ] Command flags
- [x] custom argument types

It would also be helpful to have some advanced examples and best practices.

**Comment by BlackGoat** [comment]
This is now in progress, see #220

**Comment by Inscrutable** [comment]
PR #220 is done, but the Command Flags still need documenting (there is only a placeholder).

**Comment by RobertHerhold** [comment]
@12AwsomeMan34 How is the [feature/flags](https://github.com/SpongePowered/SpongeDocs/tree/feature/flags) branch coming along? Are you still working on it?

**Comment by 12AwsomeMan34** [comment]
It's nearly finished. There's still a couple of topics to poke at and some cleanup to do. Should be ready for review sometime this weekend.

**Comment by RobertHerhold** [comment]
Resolved in fbfd67a
