### ISSUE TITLE
Alternative Installation instructions

### ISSUE THREAD

**Issue by FerusGrim** [SpongePowered/SpongeDocs#215]
Referring to [installation.rst].

Many of the instructions for Sponge are now obsolete (or, at least, the alternative, easier process should be documented), given the command-line functionality of the Sponge jar.

I'm, of course, referring to:
```console
java -jar sponge.jar install
java -jar sponge.jar run
```

Or, even simpler, a command which does both:
```console
java -jar sponge.jar go
```

[installation.rst]: https://github.com/SpongePowered/SpongeDocs/blob/master/source/server/getting-started/installation.rst

**Comment by Mumfrey** [comment]
It should be noted that installing Forge and using Sponge as a mod should always be the preferred course of action. The self-installer is intended for headless servers primarily.
