### ISSUE TITLE
Mention fallback command executor for CommandSpec child commands

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#217]
It is possible to set a fallback executor that will be executed if no child command was found:

CommandSpec.setExecutor(fallback).setChilds(subcommandMap).build()

**Comment by boformer** [comment]
Related: https://github.com/SpongePowered/SpongeAPI/commit/438059691db47b8f620d22a9b876ac0d6189b9cd

**Comment by saladoc** [comment]
This is covered in the note at the bottom of [the Child Commands page](https://github.com/SpongePowered/SpongeDocs/blob/master/source/plugin/basics/commands/childcommands.rst).
