### ISSUE TITLE
Code Modularization

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#227]
We should explain how to organize and modularize Java plugins.
- Singleton pattern (`pluginclass.getInstance()`)
- Constructor injection (simple without injection libraries)
- Static utility classes

This could be a part of the "best practices" page.

**Comment by 20zinnm** [comment]
I'm on it, @boformer :smile:

**Comment by kinggoesgaming** [comment]
Also plugin instance injection is also possible, and could be mentioned

**Comment by Inscrutable** [comment]
I'm going to close this ancient issue. It hasn't had any traction in years and it's very low priority.
