### ISSUE TITLE
Gradle Plugin Template

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeDocs#233]
The plugin templates page (plugin/basics/templates) still lacks a gradle template and the instructions how to create a plugin from it.

https://github.com/spbp could prove interesting for this.

**Comment by Mumfrey** [comment]
This is what [the official SDK](https://github.com/SpongePowered/Sponge/tree/master/sdk) is for.

**Comment by ryantheleach** [comment]
Which last we checked was blocked, https://github.com/SpongePowered/SpongeDocs/issues/209

**Comment by kashike** [comment]
SDK needs to be updated.

**Comment by Inscrutable** [comment]
Can anyone give an update on this? Is the issue still relevant?

**Comment by Minecrell** [comment]
This is covered by https://docs.spongepowered.org/master/en/plugin/project/gradle.html, IMO
