### ISSUE TITLE
Selector Documentation

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#238]
https://github.com/SpongePowered/SpongeAPI/pull/577#issuecomment-105137567

Has just gone from WIP to review status, making an issue so this will not be missed.

I fear that whilst awesomely useful, unless well documented and used by the first few plugins that get released for sponge, it will go missed by the userbase which would be a huge shame, as having some universal notation that just works with a lot of commands would be hugely beneficial.

**Comment by zml2008** [comment]
Really, most plugins won't have to deal with selectors unless doing custom command arguments -- these will be handled by Sponge's builtin command arguments, which should also be mentioned in the docs.

**Comment by ST-DDT** [comment]
Waiting for https://github.com/SpongePowered/SpongeAPI/pull/1883 and https://github.com/SpongePowered/SpongeCommon/pull/2033 .
