### ISSUE TITLE
Pagination Service

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#239]
https://github.com/SpongePowered/SpongeAPI/commit/04f11fb900d608320857989fdf9fa9da93ff7b6d

Added a new pagination service, running on the assumption that it was supposed to be committed, there should be docs explaining this as the best way to display lists to connected in game players.

**Comment by RobertHerhold** [comment]
If nobody objects, I'd like to document this one. My thought is to put it as a subcategory to the "Creating Text" page

**Comment by BlackGoat** [comment]
Sounds good to me. If the Text API gets hairy enough (ie spills over many pages), it may need a sub-folder of its own to organise them.

**Comment by RobertHerhold** [comment]
In my changes (not pushed to fork yet) I have the main Text page and the Pagination page already split up under a common text folder

**Comment by boformer** [comment]
Sounds good.
