### ISSUE TITLE
Economy Services example needs changing.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#241]
There is significant chatter in #spongedev that an official economy service of some kind will be implemented into SpongeAPI.

I'd suggest changing the example service provided to another example that is less likely to be included in the API, so it avoids confusion.

**Comment by BlackGoat** [comment]
There are indeed plans afoot for a rudimentary Economy API, although there is (obviously) no ETA. 
So it does make sense to pick a new example.

**Comment by boformer** [comment]
Do you have one?

**Comment by BlackGoat** [comment]
Something entirely fictitious would be good, so it has a low chance of becoming API ;)
How about a service for %cybernetic, that could interact with 'Neural Interfaces' and other perks.

**Comment by boformer** [comment]
There is still no official eco API, right?

**Comment by BlackGoat** [comment]
It's still WIP. https://github.com/SpongePowered/SpongeAPI/pull/675
Just trying to be ready when it arrives.

**Comment by Tzky** [comment]
EconomyAPI is finally in and we ran into this exact issue. We still need a better example than Economy.

**Comment by ryantheleach** [comment]
the problem with something very fictional, is that it's harder to understand. How about a warp service that allows other plugins to register locations with names?

**Comment by boformer** [comment]
or a ``/mail`` service?

**Comment by saladoc** [comment]
That's actually a great idea. Contexts can determine if / which mail a player can send. Some auctioning system (-> another Plugin) could send you notifications or money or items (think your average MMO Auction House...

**Comment by Tzky** [comment]
@boformer Didn't you implement such a plugin some time ago?

**Comment by Inscrutable** [comment]
Good idea, as long as it doesn't end up in the API as well :) If it happens to end up in a simple plugin, it could do double service and be hosted on cookbook too.

**Comment by boformer** [comment]
> Didn't you implement such a plugin some time ago?

That's right, but it does not provide a service and concentrates on serialization. It is also out of date.
