### ISSUE TITLE
Explain contexts.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#242]
Contexts are a core idea to implementing a permissions service, and is looking to also be used in a pending economy API.

As it is now available to use in other services, it might be worth explaining contexts, and how they can be used in plugins or custom services.

**Comment by saladoc** [comment]
I second this, the ContextualService deserves a proper explanation.
I think this should be featured in the advanced section once SpongePowered/SpongeAPI#675 is merged.

**Comment by BlackGoat** [comment]
IP-related contexts also need documentation: https://github.com/SpongePowered/SpongeCommon/commit/71220742baf4b0317ddefe625b12cc64a7ec9084

**Comment by boformer** [comment]
From the forums:

> I was busy implementing the Economy API when I noticed Set<Context>, but how do I create a global context?
What is the point of REMOTE_IP_KEY, LOCAL_HOST_KEY, LOCAL_IP_KEY and LOCAL_PORT_KEY?
Contexts are poorly explained in the Javadocs.

(CrazyPyroEagle)

My Reply
----------

A global context is just an empty ``Set<Context>``.

A word on the different keys: You don't have to implement all existing keys, and you can also add your own custom keys.

For example a context key "time" with possible values "day" and "night" (people can not access their bank account at night, something like that).

To do that, just implement a ``TimeContextCalculator``:

```java
public class TimeContextCalculator extends ContextCalculator<Player> {

    public void accumulateContexts(Player subject, Set<Context> accumulator) {
        Context timeContext = new Context("time", isInDaytimeDimension(subject) ? "day" : "night");
        accumulator.add(timeContext);
    }

    public boolean matches(Context context, Player subject) {
        if(context.getKey().equals("time")) {
            return (isInDaytimeDimension(subject) == context.getValue().equals("day"));
        }
        return false;
    }

    private boolean isInDaytimeDimension(Player player) {
        return ...;
    }
}
```

That's also how you would implement the default context keys.

**Comment by ST-DDT** [comment]
Does this require additional explanation than what is already present in the [Permission - Context](https://docs.spongepowered.org/stable/en/plugin/permissions.html#contexts) docs?

**Comment by ryantheleach** [comment]
@ST-DDT That pretty much covers it, apart from the fact that it's somewhat expected that ContextCalculators are threadsafe.

**Comment by ST-DDT** [comment]
I'll add a note for that later today.
