### ISSUE TITLE
Should events be mentioned on basics/text?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#243]
From IRC.
> ryantheleach: https://docs.spongepowered.org/en/plugin/basics/text.html > The code excerpt illustrated above will return uncolored text, with no events configured.
> ryantheleach: What does that mean? "with no events configured"
> ryantheleach: is it supposed to be referring to actions like hover actions?
> minecrell: ryantheleach: seems so

This should either make direct reference to TextActions, or not be included.

**Comment by boformer** [comment]
Yes, "events" probably means "text actions".

Text actions are mentioned in the docs, so what exactly is your question?
