### ISSUE TITLE
Dynamic Event Registering: Note contradicts the rest of the page.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#244]
https://docs.spongepowered.org/en/plugin/basics/events.html

>It is currently not possible to register a dynamic event handler by providing an event type and a handler.

snip

> Dynamic Registering and Unregistering of Event Handlers
> Some Plugins may wish to dynamically register or unregister an event handler. In that case the event handler is not a method annotated with @Subscribe but a class implementing the EventHandler interface. This event handler can then be registered by calling the event managers register() method, which accepts a reference to the plugin, the Class of events handled and the handler itself.

**Comment by gratimax** [comment]
Yes, documentation is written at multiple times and is sometimes not fully consistent. However, I think I can safely say that for issues like this with an "easy fix" we would prefer it to be reported, fully fixed as a PR with the factual error rather than as an issue.
