### ISSUE TITLE
Table of Contents Ordering.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#245]
https://docs.spongepowered.org/en/about/introduction.html

The about information, and thus the introduction, is currently in the last chapter of the documentation. Wouldn't it make sense for the introduction to be before Creating a Server?

**Comment by gratimax** [comment]
The most useful information to someone looking at the documentation is how to _actually use_ what is created by the Sponge project. Going on and on about who is behind the project and what it's all about may be interesting to some people or you @ryantheleach, but that's not the final purpose of us creating this documentation. I think that we can safely assume that the majority of readers have a base level of knowledge about the Sponge project itself and really want to know how it applies to _them_. Therefore a useful introduction to the documentation would be as it is, jumping straight into the material.

**Comment by ryantheleach** [comment]
It was more just the introduction section. I figured if the Introduction and FAQ were the first things mentioned we might get less frequently asked questions asked on the forums, IRC and elsewhere.

But I understand your point of view.
