### ISSUE TITLE
Explain Message Sinks

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeDocs#247]
Essentially the idea is that they enable you to control the target recipients of a message.

See SpongePowered/SpongeAPI@48ac7a5948cd9695e39c2359c5d3adfe0fc1ecc1

**Comment by RobertHerhold** [comment]
*Assigns to myself

What would be the most logical directory for the page? It could arguably go in a `text` folder, but that could be a bit of a stretch

**Comment by saladoc** [comment]
Putting it into a `text` folder might work if the whole section was renamed to "Texts and Messaging". Advanced section seems also fitting, especially if you include information if / how custom `MessageSink`s can be created.

**Comment by RobertHerhold** [comment]
I think I'd sooner put it into the advanced section... Message Sinks probably aren't something the majority of people will need to use
