### ISSUE TITLE
Explain XML text format

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeDocs#250]
In SpongePowered/SpongeAPI#708

An older iteration was described in https://bukkit.atlassian.net/browse/BUKKIT-5245
This is another option plugins can use to represent a Text message as a string.

**Comment by RobertHerhold** [comment]
Also, the docs don't mention anything about ``Texts#toJson()`` and ``Texts#parseJson()``, which should both be included. Would we want this in the advanced section or just keep it all on the same page?

**Comment by zml2008** [comment]
maybe on the main page -- those don't need too much extra docs, you can just link to MCwiki.

However, I am considering some tweaks to how the API works to make xml and json handling a bit more consistent

**Comment by TomyLobo** [comment]
Mentioned on the implementation PR, but probably also related to this:
Decide a name for the format, since right now it's sometimes called HTML and sometimes called XML.

**Comment by me4502** [comment]
I vote ZML, standing for ZML Markup Language

**Comment by zml2008** [comment]
I started with HTML, which is what you guys called it, then switched to calling it the XML format. I'm thinking TextXML is better though since it's more specific -- any suggestions?

**Comment by Mumfrey** [comment]
*TexML*?

**Comment by gabizou** [comment]
*SML*?

**Comment by gratimax** [comment]
You don't give separate names to xml schema, you give names to something that looks significantly different. The "project object model" is called so not as another format but as a schema based on XML. I don't see why a text format on top of XML is special at all, so just call it "xml text format".

**Comment by TomyLobo** [comment]
@Mumfrey TexML sounds like it would be related to [TeX] (http://en.wikipedia.org/wiki/TeX)
@gratimax XML, for one, has a top-level tag, except if you're talking about fragments. This language has only an implicit top-level tag.whitespace also carries more significance in it than in most XML schemas.

@gabizou SML for Sponge Markup Language?
Considering that the language isn't inherently spongy, that would be a misnomer and might hinder adoption by other projects.
Remember, Sponge is MIT, which means they can just use it if they want. That's the good thing about MIT: Nothing is lost.

How about HUML - Hopefully Useful Markup Language

**Comment by zml2008** [comment]
or TMLTLM -- That Markup Language TomyLobo Made

I've just gone with TextXML in most places, since it is pretty much XML (implicit <span> excluded)

**Comment by gabizou** [comment]
How about Github Markdown?

**Comment by ryantheleach** [comment]
How about people stop bikeshedding over the name, wrap it in a root node, and make it real xml, whitespace included? To have something like xml but not is how you start making people very very confused.

**Comment by zml2008** [comment]
no. again, that trashes usability Nobody wants to have to remember to wrap stuff in <span>. 
for the name, I think this is close enough to XML (lenient XML, root node optional), that we can call it the Text XML format. Discussion done.

**Comment by RobertHerhold** [comment]
Closing in favor of #293

**Comment by TomyLobo** [comment]
@zml2008 "lenient XML" - it's called an XML fragment :)
