### ISSUE TITLE
What's your feedback on the PR building system?

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/SpongeDocs#253]
Over the past couple weeks I have experimented with a new static-site build system. It's primarily motivated by my experience working on the Sponge documentation in using Travis, Sphinx, and Crowdin, as well as building the current PR previewing system.

For those of you who don't know, by my design Spongy [builds every PR](https://github.com/Spongy/SpongeDocs-PRs) made to SpongeDocs. However, due to limitations with secure keys handled by Travis, only PRs made by collaborators have the preview feature fully working. To be more specific, Travis does not permit secret keys when it runs builds on repositories that are forks of the main repository, meaning that we do not have enough information to deploy.

This new system that will under development will be able to build and host PRs as well as the main documentation, for anyone making PRs to SpongeDocs (and in fact any github repository that adopts this system). This system isn't an official Sponge project and likely never will be, but if I do work on it I will make sure to integrate it with the Sponge documentation so that SpongeDocs can get the full experience.

Anyway, I would really like feedback on the current PR previewing system in the form of an answer to this question: "Do you find the PR previewing system useful?"

Pinging @SpongePowered/docs for thoughts.

**Comment by BlackGoat** [comment]
Very Very Very Very much so. The weird intricacies of Sphinx and rst on the Docs sometimes baffle me, and the preview gives me a heads up when I goof in a way that Travis just can't.

**Comment by RobertHerhold** [comment]
I agree. It's nice to see the "final product" of sorts so you can see if there's anything to be changed before it's pulled in. For me, it would be much harder to look at an rst file and spot an error rather than look at the actual docs preview

**Comment by Tzky** [comment]
I can just +1 the above said. I think a review system is absolutely needed, as novice docs contributors can view their changes before merging. This way a) the final look of the PR is shown b) typos and wrong commands can be fixed easily.

So yes, i absolutely find this PR preview system useful.

**Comment by AnUnknownMiner** [comment]
:+1:  :100:  :yellow_heart:  Yes please!

**Comment by Inscrutable** [comment]
I believe it is appropriate to close this now all feedback is done, unanimously in support.
