### ISSUE TITLE
Glossary for SpongeDocs

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#254]
There was feedback that some of the reserved words and terms we use on the Docs may be unfamiliar to newcomers. One way to help resolve this would be to have a Glossary. To this end, I have prepared a [basic draft](https://docs.google.com/document/d/10HbSShruPjpkT9lwi49FuCZ-AwktXEPZqPzQ2TdsUHs/edit?usp=sharing) of the terms we use that may need defining. Input is welcome on the content, placement, and very existence of this page.

**Comment by Tzky** [comment]
Left some comments and suggestions.

**Comment by BlackGoat** [comment]
The Draft Glossary has been re-drafted, taking on board most of the suggestions. It seems links would be a useful addition (to internal or external pages, as appropriate), so some are suggested. Still WIP.

**Comment by boformer** [comment]
Some more:

Cataloged type - a replacement for Java enums (which can not be extended at runtime).

Service

Interface (Java)

**Comment by BlackGoat** [comment]
We aren't trying to teach Java, nor do we want this crowded with technical definitions. This is primarily a user-facing Doc, intended to introduce newcomers to the basic terminology of Minecraft servers, Forge and Sponge. I'd like to keep it limited to the most common *reserved words* we use.
A technical glossary of Java terminology may prove a useful addition, although some of the suggestions (eg Cataloged TYype > enum) may also fit into "best practices".
