### ISSUE TITLE
Update Block Documentation

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeDocs#263]
Block Documentation must be updated.
- [ ] Update Code Examples
  - [ ] compare `BlockType`s using `.equals()` instead of `==`
  - [ ] rename all Location parameters from block to blockLoc
- [ ] reference to Data docs where possible
- [ ] Explain BlockTraits

**Comment by saladoc** [comment]
Updated description, will tackle this after data api docs.

**Comment by Tzky** [comment]
from nitpicking #298 :
- [ ] Page: plugins - blocks: rename all Location parameters from block to blockLoc

**Comment by 12AwsomeMan34** [comment]
@saladoc What's your progress on this so far? If you haven't gotten too far, I'd like to try my hand at this.

**Comment by saladoc** [comment]
As I'm currently preoccupied with various other stuff (mostly RL), your support would be most welcome. My apologies, I should have removed my assignment.
