### ISSUE TITLE
Mention "OpLevels" and default permissions enabled for sponge.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#266]
service.getGroupForOpLevel(1).getSubjectData().setPermission(SubjectData.GLOBAL_CONTEXT, "minecraft.selector", Tristate.TRUE);
                    service.getGroupForOpLevel(2).getSubjectData().setPermission(SubjectData.GLOBAL_CONTEXT, "minecraft.commandblock", Tristate.TRUE);

Those 2 lines set the permissions for minecraft.selector and minecraft.commandblock to true for whichever groups "OpLevel 1" and "OpLevel 2" represent in whichever permissions service is installed.

**Comment by zml2008** [comment]
These defaults are only set for the fallback permissions -- any other permissions service doesn't have to have a concept of op levels.

If the permission service is not Sponge's builtin, the only defaults that are applied are for commands that all users get by default normally.
