### ISSUE TITLE
Add YAML documentation

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#280]
With the addition of YAML, there's a need to document it's availability.
That said we should:
* update the docs to mention YAML
* mention shaded YAML dependency
* mention that HOCON still is (and will be) the preferred and only officially supported format
* provide a way and/or docs for YAML -> HOCON conversion

Relevant:
https://github.com/SpongePowered/SpongeAPI/issues/699#issuecomment-115333786

**Comment by BlackGoat** [comment]
I browsed through the docs and identified these pages that may need tweaking for this issue: 
* server/getting-started/configuration/hocon
* plugin/basics/configuration.
* plugin/advanced/config-in-depth/index
* server/getting-started/configuration
A YAML page is probably not a good idea; a link to http://www.yaml.org/spec/1.2/spec.html would be better. We need to do our best to discourage the use of YAML, but it will still be possible to use it.
