### ISSUE TITLE
Properties Table for global.conf needed

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#289]
We should detail the sponge properties in a Table to allow translation of the Code block comments, and to generally resemble the adjacent server.properties page. Some might need small examples, such as the Alias feature, and some could benefit from a longer explanation (such as entity activation ranges). Renaming the docs page from sponge.conf to global.conf may also be a good idea.

**Comment by ryantheleach** [comment]
2:06 AM <+zml> Inscrutable: alias like commands? that's for choosing which plugin gets a specific command when multiple request it. so it's unqualified command to plugin name -- for example me=Minecraft, give=Essentials
2:06 AM <+zml> *multiple plugins provide it

**Comment by BlackGoat** [comment]
Groovy. We also need to know what the status of sql properties is, as it no longer appears in the default global.conf - but still seems to be present in the Sponge codebase.
