### ISSUE TITLE
Texts documentation examples needs proof-reading.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#292]
Multiple changes have happened to the Texts documentation since it was last edited, and we are getting several questions of the forums about it.

https://forums.spongepowered.org/t/translating-alternate-color-codes/8353/2

**Comment by RobertHerhold** [comment]
This is not so much that there were changes, but that we never documented going to/from legacy, xml, and json.

See #293

**Comment by ryantheleach** [comment]
Yeah ok, I should have double checked the docs before creating the issue, I shouldn't trust people blindly.
