### ISSUE TITLE
Clarify documentation on command aliases for global.conf

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeDocs#294]
Currently the docs for the Global config on command aliases are rather lacking: 
[docs](https://docs.spongepowered.org/en/server/getting-started/configuration/sponge-conf.html?highlight=aliases)
The good thing is that we can make ti better by adding a comment for an example! Such as found on this thread: https://forums.spongepowered.org/t/overwriting-built-in-commands-via-global-conf/8397/2

**Comment by BlackGoat** [comment]
Been there, done that. Yesterday, in fact. https://github.com/SpongePowered/SpongeDocs/pull/291
It was in progress even before the conversation on the Forum ;) Take another look at that docs link.

**Comment by Inscrutable** [comment]
This was renamed from alias to commands, and seems to have been purged from the global.conf docs in January. Can we get this re-added ASAP? The alias feature is pretty important for users to be able to unsnarl plugin command conflicts.

**Comment by Inscrutable** [comment]
This was renamed from alias to commands, and seems to have been purged from the global.conf docs in January. Can we get this re-added ASAP? The alias feature is pretty important for users to be able to unsnarl plugin command conflicts.

**Comment by Inscrutable** [comment]
This was renamed from alias to commands, and seems to have been purged from the global.conf docs in January. Can we get this re-added ASAP? The alias feature is pretty important for users to be able to unsnarl plugin command conflicts.

**Comment by saladoc** [comment]
Is this change already in beta or does it only apply to later versions?
