### ISSUE TITLE
Configurate 2.0 Changes.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#295]
Unsure what's changed yet but figured I'd post this as an issue to make sure it isn't missed.

https://github.com/SpongePowered/SpongeCommon/compare/c04062a1cb47...18188da5edf8

Changelog: https://github.com/zml2008/configurate/commit/6ea2186647048a521a60870c28288e99bef3174a

+ guice object mapping? https://github.com/zml2008/configurate/commit/34126f08bf3dd4833eebad11a27b5f8506a6e8ff

At minimum we should add docs for the TypeSerializer and double check that the way to get configs for plugins hasn't changed or their isn't a better option then the @inject annotations.

This also seems to have added support for DataSerializable which means anything that uses DataSerializable in the DataAPI should be able to be saved out to configs if it couldn't previously.

@zml2008 anything major that I've missed?

**Comment by zml2008** [comment]
guice object mapping allows you to have an @Inject constructor on your config object and if given a `GuiceObjectMapperFactory` (which is @Inject-able) in the ConfigurationOptions, can create the new configuration object using objects available to the plugin as Inject fields (so the plugin instance, game, etc). In the main plugin this would look like:

```java
@Plugin(name="MySuperCoolPlugin", id="mysupercoolplugin", version="toocoolforversions")
public class MySuperCoolPlugin {
    @Inject private GuiceObjectMapperFactory factory;
    @Inject private ConfigurationLoader<CommentedConfigurationNode> loader;

    @Subscribe
    public void enable(PreInitalizationEvent event) {
        CommentedConfigurationNode node = loader.load(ConfigurationOptions.defaults().setObjectMapperFactory(factory));
        MyConfiguration config = node.getValue(TypeToken.of(MyConfiguration.class)); // whee
    }
}
```

The biggest change (and the reason it is 2.0 as opposed to 1.3) is a rather large refactor of TypeSeralizer registration to allow non-global TypeSerializer registration and hopefully performance improvements, and to remove some redundant stuff in TypeSerializer implementations -- this is breaking for anybody who provides a custom TypeSerializer.
