### ISSUE TITLE
Event refactoring

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#323]
*"Everything is changing, Everything is changed" - Big Weird Thing, Stannard Ridgway.*
A major rewrite of the plugin/events doc will be needed, as massive API changes are imminent.
The merge of the new Event API is fast approaching, look for refactor/event-names.

Via @gabizou : "There is no PR (mostly because literally EVERYTHING is changing). Commit messages and javadocs in various places should provide a lot of information, especially the api.event.package-info.java javadocs. We need someone to review event changes in API, and start preparing to overhaul the docs on events, because there are a LOT of changes in structure and usage. " 

Here are the main commits: https://github.com/SpongePowered/SpongeAPI/commit/36ba40439d38eaade3833bd45048849742ff79d2 and https://github.com/SpongePowered/SpongeAPI/commit/ce6ee8df257ac111ea9474cb4515c09dcb3458fa

**Comment by kashike** [comment]
Docs are missing information on how to register a class as a listener: https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/service/event/EventManager.java#L37-L49
https://github.com/SpongePowered/SpongeDocs/blob/master/source/plugin/events.rst#event-handlers

**Comment by RobertHerhold** [comment]
Addressing this in #328
