### ISSUE TITLE
Update SpongeDocs to Java8

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#324]
With the recent announcement that Sponge will (finally) move to Java8 and drop support for 6 and 7 the Docs now must get updated to fit Sponge.

reference: 
https://forums.spongepowered.org/t/theres-a-java-update-available/9147
PR adressing this Issue: #325

**Comment by Minecrell** [comment]
We should also extent the docs to provide more help with installing Java 8, especially on quite frequently used distributions like Ubuntu Trusty (14.04 LTS) where no official openjdk8 build is available yet. It would be good if we have a clear explanation how to update for users not that experienced with this kind of stuff.

**Comment by boformer** [comment]
That means we have to redo every code snippet which contains ``Optional``s...

**Comment by gabizou** [comment]
> That means we have to redo every code snippet which contains Optionals...

Sounds about right. But it's just an import change and `fromNullable` to `ofNullable` and `orNull` to `orElse(null)`.

**Comment by Inscrutable** [comment]
Only two pages need to change java version (J6/7 -> J8): server/getting-started, & preparing/jdk.
The rest seems to involve reviewing code snippets for ``Optional``.
(We should make sure this isn't merged until the master branches are similarly tweaked.)

**Comment by Tzky** [comment]
I started working on this in java8 branch. Feel free to push your changes there :)
