### ISSUE TITLE
Events page polishing

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeDocs#337]
- Check code examples and class name mentions if they are up to date
 - remove `Callback` section, according to Zidane those might vanish soon(tm)
 - document the [SpongeEventFactory](https://spongepowered.github.io/SpongeAPI/index.html?org/spongepowered/api/event/SpongeEventFactory.html)

**Comment by Kasuko** [comment]
I submitted a pull request regarding this issue as #340. Let me know what I can do to make it better.
