### ISSUE TITLE
Art assets are missing

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#346]
Just a reminder for myself:

* picture of Spongie 
* official logo / Banner

are both still missing on the docs.
Specifically here: https://docs.spongepowered.org/en/about/assets.html

**Comment by Inscrutable** [comment]
Should we present .jpg versions and links to vector files? I have the latter assembled in a [Google Docs folder](https://drive.google.com/folderview?id=0B2eJoDqi_uVjU3o3ZG14T0F0ZGs&usp=sharing), along with the brand assets guidelines.

**Comment by Tzky** [comment]
Please discuss any issues in the corresponding PR #348
