### ISSUE TITLE
Add missing imports

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeDocs#354]
There are several articles that are missing imports in code blocks - they need to be added.

**Comment by Tzky** [comment]
I'm not sure if we need this issue. Isn't your PR #353 and Issue #329 enough?

**Comment by saladoc** [comment]
I did not find any mistakes with this.

**Comment by RobertHerhold** [comment]
@Tzky #353 removes repeated imports, while this is for missing ones, such as in https://docs.spongepowered.org/en/plugin/configuration/loaders.html. 

@saladoc I'll assume you meant to comment on my PR instead of in here.

**Comment by saladoc** [comment]
True, I got the tabs mixed up....
