### ISSUE TITLE
Mention the Cookbook on the Docs

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#366]
Currently the Cookbook (https://github.com/SpongePowered/Cookbook) isn't mentioned on the Docs. We should add at least a simple link to attract some users as the cookbook might help newbies which aren't familiar with the SpongeAPI yet.

**Comment by RobertHerhold** [comment]
Will put [on this page](https://docs.spongepowered.org/en/plugin/index.html)

**Comment by Inscrutable** [comment]
A link to cookbook is definitely a good idea, but I hope it doesn't disappear in there. I believe we should try to do something to group the links on the Plugin Index page, to assist in readability. (It's a pity we can't use 2 columns, but I digress). I may make an issue for that, if there is anything we *can* do...

**Comment by Tzky** [comment]
hmm, 2 columns to have the TOC split in half?
