### ISSUE TITLE
Index TOC in 2 columns

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#367]
I believe we should try to do something to group the links on the Main and Plugin Index pages, to assist in readability. [continued from #366 ] Two columns (with Toctrees inside a table) seems to be possible, thanks @Tzky. Let's work on *How* we reorganise *what*. :)

**Comment by Tzky** [comment]
Example code how this could work: https://gist.github.com/Tzky/f4d072de5d6d06a4421f
Preview: 
![toccolumn2](https://cloud.githubusercontent.com/assets/10940670/10996946/667db7a6-8489-11e5-9755-5623de08677c.png)

**Comment by Tzky** [comment]
I'll close this for now as i closed the PR too.
