### ISSUE TITLE
Explain AI tasks and goals

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#377]
The AI API is getting finished soon, so we need to document:
- [ ] how it works
- [ ] what tasks are
  - [ ] how you implement your own tasks
- [ ] what goals are
- [ ] how to use/alter the Vanilla AI or a Mod AI
- [ ] how to implement your own AI
- [ ] explain all available events
  - [ ] .AITaskEvent.Add/Remove

**Comment by ST-DDT** [comment]
I'll try to write something for this. Might take a while though.
