### ISSUE TITLE
Document Aikars timings

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#380]
Aikar's Timings Viewer (https://github.com/aikar/timings) got included into Sponge, so we need to document:
 - what it is
 - what it does
 - usage examples
 - configuration (if available?)
 - limitations (what isn't tracked)
 - how plugins can implement their own timings (thanks @ryantheleach )

**Comment by Inscrutable** [comment]
The command ``/sponge timings report`` generates a report on Aikar's site. It only tracks six things at present as far as I know, and plugins aren't amongst them. I don't know if there are any other flags.
We should only list what it *does* track, a list of what isn't tracked would be endless. ;)

**Comment by ryantheleach** [comment]
As well as how plugins can add their own timing points.

**Comment by Inscrutable** [comment]
The first bit of this belongs on the [Sponge Commands](https://github.com/SpongePowered/SpongeDocs/blob/master/source/server/spongineer/commands.rst) page, or as a new page within the *spongineer* folder (depending on how wordy it gets). 
Adding timings to plugins is a whole different kettle of fish, and would need a new page within the  *plugin* hierarchy, when someone feels like explaining it.
