### ISSUE TITLE
Add favicon.ico to the Docs

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#385]
Currently the Docs use the standard Sphinx favicon. Kenzierocks suggested that we should introduce a customized favicon for the docs.

Solving this issue requires:
- [ ] adding a ``.ico file`` to the static path of the SpongeDocs theme
- [ ] setting up ``html_favicon`` in ``conf.py`` to point to said ``.ico`` file

conf.py:
```
html_favicon = 'favicon.ico'
```

Corresponding PRs:
SpongePowered/Sponge_Docs_Theme#9
#386

**Comment by gratimax** [comment]
Merged the PRs

**Comment by Tzky** [comment]
Perfect, thanks!
