### ISSUE TITLE
Can you add Sponge's Patreon Page in Sponge Glossary

### ISSUE THREAD

**Issue by LOLDERP** [SpongePowered/SpongeDocs#388]
Can you at least put it somewhere in the docs 
since im only new to java i can't help with spongeforge and spongevanilla
so this the best i can do
currently try to find missing stuff in SpongeDocs

**Comment by Tzky** [comment]
Addressed this in #384, added link to Patreon at the bottom of the index and on the glossary.

Thank you for the suggestion! :)
