### ISSUE TITLE
Config package name changed

### ISSUE THREAD

**Issue by sibomots** [SpongePowered/SpongeDocs#391]
The example might be out of date:

Listed: https://docs.spongepowered.org/en/plugin/configuration/index.html

import org.spongepowered.api.service.config.ConfigDir;
import org.spongepowered.api.service.config.DefaultConfig;

Shouldn't it be:

import org.spongepowered.api.config.ConfigDir;
import org.spongepowered.api.config.DefaultConfig;

Just checking.

**Comment by Inscrutable** [comment]
You may be right, it's probably somewhere in [here](https://github.com/SpongePowered/SpongeAPI/commit/ff668f2b98c007d615003a2c82eea9e8e9b24b91). We're still assessing the scale of these changes (see issue #390), and I'd be more than happy for a little help ;)
