### ISSUE TITLE
Code examples should be compilable and linked using literalInclude.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#393]
At the moment every time that SpongeAPI undergoes breaking changes the docs examples break, This is worse then plugins breaking, because plugins can be compiled, and the errors are rather obviously output by the compiler.

It would also be a boon to users to have a hard example, that works, and can view the complete plugin that the snippet came from, if they wish.

The Sphinx directive literalinclude can include snippets from arbitrary locations. and better yet, can dedent, list only lines specified, or filter lines based on content.

This would allow for comment tags //SpongeDocsStart-CommandRegistrations marking the start and end points.

http://sphinx-doc.org/markup/code.html#directive-literalinclude

This would also have the added benefit, of possibly adding the plugin build to the CI testing, so that as soon as sponge breaks, the next commit will fail and we will be immediately notified.

**Comment by boformer** [comment]
That looks great. Only problem might be that the line numbers must be specified. I don't think that the auto-detection works for java code.

**Comment by TBotV63** [comment]
`start-after` and `end-before` could be a solution to that.

> Another way to control which part of the file is included is to use the start-after and end-before options (or only one of them). If start-after is given as a string option, only lines that follow the first line containing that string are included. If end-before is given as a string option, only lines that precede the first lines containing that string are included.

They should work with any type of file.

**Comment by boformer** [comment]
Ok, that would work:

```java
// begin docs-example
public int x() {
    return y;
}
// end docs-example
```

**Comment by TBotV63** [comment]
The example name would have to be included in the comment tho I believe, otherwise there could be issues with files that contain multiple examples. (Even if this is to be avoided in many cases, better safe than sorry.)

**Comment by boformer** [comment]
yes.

**Comment by Inscrutable** [comment]
I have a small concern here, that the development and maintenance of this kind of system may be more work than actually doing it "the hard way". Implicit in the concept is the maintenance and updating of a nebulous quantity of plugins. It also adds a layer of complexity and automation that needs to be documented itself, and adds to the burden of maintenance. 
Just some points to consider - I'm not against the idea in principle, I just don't want to see an over-engineered solution that could discourage contributions.

**Comment by boformer** [comment]
We can just create a separate repo for the code examples to validate them. The plugin is not required.

Then we just have to update the docs manually when the code changes.

**Comment by saladoc** [comment]
I'm not a fan of the "code examples should be compilable" rule.

I'd like to have the opportunity to leave out boilerplate for the docs, to be able to just assume that a variable foo that holds a `Foo` exists and has a sane value. Sure, I like code examples to be compilable, yes. But I think trying to enforce that would be a grave mistake, as the docs are not meant to be a source of copy-paste code. The example code is to be read and understood by aspiring spongineers, not the java compiler. It compiling is nice but should not be a requirement.

**Comment by TBotV63** [comment]
> I'm not against the idea in principle, I just don't want to see an over-engineered solution that could discourage contributions. 

Overengineered solutions are my speciality. ^^

> as the docs are not meant to be a source of copy-paste code

You can still hide the boilerplate away and limit what is shown in the docs.

The primary advantage of this (as I catch it) is that errors are reported early. If code is compilable and is run on CI to test, there is an instant warning that some example is broken. It makes finding documentation problems and fixing them easier.

On the work of converting and maintinaing the system:

I can see how converting all examples to it would be quite a load, but maintaining it shouldn't be any harder than it is now, it'd just take some workflow adjustments.

**Comment by RobertHerhold** [comment]
What @saladoc said.

Also, the API *shouldn't* be having many breaking changes anyway so any existing code blocks shouldn't need to be compiled all the time. With regard to new documentation written, it is the doc writer's responsibility to make sure their own code compiles and works properly.

**Comment by ryantheleach** [comment]
I didn't make this issue because I thought it would be easier then the current system, but figured it would assist in accuracy. Not only would it find errors faster as the API is updated, but it would work to catch human errors that the docs maintainers might miss.

**Comment by ST-DDT** [comment]
While such a tool sure might be useful there are plenty of cases where code examples are simplified or abbreviated so they wouldn't compile. Mostly during variable initialization or referencing arbitrary `doMagic()` methods.

I did the latest code update runs on the repo and IMO its somewhat possible to to this with a little script and some time. I will publish that script soon as a tool in SpongeDocs. So having a separate code source seems unnecessary to me.

The only case where this would really be useful is when we would support bleeding edge APi versions and API PRs would be forced to create an accompanying Docs PR:

**Comment by Inscrutable** [comment]
This issue is as old as the hills, and no progress in over 2 years gives me an excuse to close it.
If ST-DDT's new script tool makes checking old code faster, then that will have to do.
