### ISSUE TITLE
Major difference to Bukkit event system.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#396]
A lot of sponges events are recorded, that is to say, that cancelling changes on block events or setting block transactions as failed, result in the blocks in the world changing, and being set back.

This means that side effects from the blocks changing will still take effect if cancelled.

Redstone will create "instant" pulses, neighbouring blocks will be notified (block updates), and FallingBlock entities will still spawn / fall.

Talking to @bloodmc in IRC makes it seem that this is a fundamental difference in implementations and is unlikely to change.

**Comment by Inscrutable** [comment]
This should be included as a *Note* on the [Working with Events](https://github.com/SpongePowered/SpongeDocs/blob/master/source/plugin/event/index.rst) index page, or somewhere within that hierarchy.

**Comment by ST-DDT** [comment]
@ryantheleach Are there other differences between Bukkit's and Sponge's event system other than block neighbor updating? And is this still a thing or is Bukkit long forgotten?

**Comment by ryantheleach** [comment]
In the eyes of the Sponge community it's largely a thing of the past, but Spigot is still strong and proud, a migration page on what concepts are surprisingly different, what concepts are largely the same, and the extra features bundled in Sponge may well flip a few developers who were previously still developing on Spigot to Sponge, and honestly in a community of our size, just a few large, well surpported plugins to do some tasks would make a huge difference to server owners.

The problem is, it would take someone like @me4502 Who is intimately familiar with both, to come up with some talking points.

The original post regarding block neighbor updates I'm not sure that's necessarily correct any more, but it would need retesting to see.

**Comment by Inscrutable** [comment]
I can't see much value in keeping this ancient issue alive. Unless someone wants to get behind it and detail the specifics, it can stay closed,
