### ISSUE TITLE
Data Manipulator example incorrectly describes `get` method

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeDocs#398]
In the` Data Manipulators` section of the Data API docs, `HealthData` used as an example of working with `DataManipulators`. One section reads (emphasis mine):

>First we need to check if our target has health data. We do so by first asking it to provide us with its health data by passing its class to the get() method. We get an Optional which we can use for our check. This Optional will be absent if either our target does not support HealthData or if it supports it but at the present moment does not hold any health data. **In the second case there is no data manipulator since the data represented by it would not differ from the manipulator's default values. Since we can safely assume that if a data holder has the default HealthData, it will already be at its full health, we won't need to heal it.**

However, this emphasized section is incorrect. If a `DataHolder` supports a particular manipulator (with `#supports()`, then `#get()` returning the empty Optional means that the data *is not present at all*. While this will never be the case with `HealthData` (any `DataHolder` that can have health will **always** have health), some `DataHolder`s will exhibit this behavior with certain `DataManipulator`s.

This is a critical distinction to make, as data not being present can have a fundamentally different meaning from 'present-but-empty' or 'present-with-default-value`. For example, `DisplayNameData` is supported by any `Entity`, but only Humans have it present all the time. However, a entity (a `Pig`, for example) with no display name is *very different* from a `Pig` with an empty display name. The former will display normally to the client, while the latter will have a nametag above its head when looked at (though an empty one).

I wrote a comment about this [here](https://github.com/SpongePowered/SpongeCommon/issues/8#issuecomment-165221702), though it was mainly intended for the contribution docs. While plugin devs don't need to care about how this specifically relates to `DataProcessors`, in might be useful in some form. I'll probably open a PR working some form of it into the main Data API docs.

**Comment by Tzky** [comment]
Time to blame @saladoc.

**Comment by saladoc** [comment]
way to go @saladoc you moron
