### ISSUE TITLE
DataManipulator Docs Outdated

### ISSUE THREAD

**Issue by oliverdunk** [SpongePowered/SpongeDocs#404]
#404 ISSUE NOT FOUND
But seriously...

Several parts of the Data API have been changed after the last few weeks, but the docs have not been updated to reflect these meaning they are either misleading or they are no longer correct.

- [ ] In step six, reflect the renaming of SpongeSerializationRegistry to the new class.
- [ ] Add basic documentation for DuelProcessors as these are currently not mentioned.

Presumably these should be fixed as part of a larger PR covering several other changes.

**Comment by saladoc** [comment]
Thanks for reporting, Those points have been merged into the Data API Issue. 
Closing in favour of #335.
