### ISSUE TITLE
Introduce new branching and versioning model for the Docs

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#414]
With the release of API 3.0.0 the Docs need to follow the other repos in terms of versioning and branching to allow for targeting a single API version. I'd prefer a KISS approach and this is what @saladoc and i came up with so far:

1. The Docs target the latest API release (currently 3.0.0)
2. The Docs get built off ``master`` branch
3. Every feature/addition/fix to the Docs which applies for the latest ("current") API release gets pulled into master directly
4. Every feature/addition which targets a future version stays out of master till the Docs target the said new API version
5. Every PR which doesn't target the current API release gets a label with the targeted version
6. If a new API version is released, Docs version gets bumped via a "bump-version" commit.

Optional:

1. if there are many features/additions which target a future version, a separate "future-version" branch may be created
2. PRs get a "future-version" label *and* a specific "version x.y.z" label

How to adjust to new API release versions:

* tag current commit at master with current release version (e.g. ``git tag v3.0.0``), this commit is the latest version of the docs for the given version
* bump version (conf.py, readme, dependency listings)
* merge already prepared PRs (former "future version" PRs)

Thoughts?

**Comment by boformer** [comment]
It might be easier for new docs contributors to set the "next-version" branch as the main branch on GitHub (so that pull requests are linked with that branch by default).

> if there are many features/additions which target a future version, a separate "future-version" branch may be created

Usually the docs are written after a feature is added to the "next-version" branches of the java projects. So that should rarely happen.

> PRs get a "future-version" label and a specific "version x.y.z" label

Not really important because the branch it is targeting defines the version (usually current or next).

**Comment by Tzky** [comment]
>It might be easier for new docs contributors to set the "next-version" branch as the main branch on GitHub (so that pull requests are linked with that branch by default).

I assume that we're usually behind the API with our documentation. So currently we'd target 3.0.0 and every PR which adds Docs for 3.0.0 would get merged directly. PRs for 3.1.x and newer would go into the ``future-version`` branch or just stay unmerged and labeled with their corresponding version. I'm not sure we should make ``future-version`` the default branch, as basically every 3.0.0 PR would have to get rebased to master.

**Comment by Tzky** [comment]
This is getting addressed in #410. Closing this Issue for now. If you got further input please comment on the PR.
