### ISSUE TITLE
Document initialization process for services

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#417]
@gravityfox suggested that we standardize the initialization process for services in general and especially for the EconomyAPI. This includes the init, pre-init and post-init events.

**Comment by Flibio** [comment]
Was there a final decision on which events should include what?

**Comment by Tzky** [comment]
Don't think so. The decision is still pending... We should probably as a dev about this first.

**Comment by gravityfox** [comment]
I think the consensus was that a service should be registered in pre-init and made completely functional by the end of init.

That way it is guaranteed to be accessible during init and completely functional during post-init.

If you follow that you should be fine.

**Comment by Tzky** [comment]
I'll close this issue, please continue the discussion on the PR (#419)
