### ISSUE TITLE
Verify Entity Spawning Example

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeDocs#427]
See [this forum post](https://forums.spongepowered.org/t/how-to-create-item-entity/10691/3) for the problems that arose with it.

We need to verify if it was an error on nap's part or if the `EntitySpawnCause.builder()` is not included in 3.0.0

**Comment by 12AwsomeMan34** [comment]
Time to blame @12AwsomeMan34...

I ran some tests using the builder, and can reproduce the same [error] (http://pastebin.com/7wpEGJY1). It would seem that the ``EntitySpawnCause.builder()`` is meant for use by sponge, not so much for plugins (please correct me if I'm wrong, basing this off of the fact that there is an error when using it).

I'm not entirely sure if ``Cause.of(this)`` is a great substitute for a ``Cause``, seeing as ``Cause.of()`` will accept any ``Object``, however it seems to *work*.

Progress on this can be tracked in the [fix/spawning branch] (https://github.com/SpongePowered/SpongeDocs/tree/fix/spawning).

**Comment by gabizou** [comment]
`EntitySpawnCause.builder()` is supposed to be implemented, just hasn't been properly implemented and registered. `SpawnEntityEvent`s are still fubared in this case because when they were initially implemented, they weren't implemented with any use of `SpawnCause`s of any kind.

**Comment by napentathol** [comment]
The version of sponge I am using is 1.8-3.0.0-BETA-129
The version of the api I am using is 3.0.0

**Comment by 12AwsomeMan34** [comment]
@gabizou 
Thanks for the clarification, does this mean the issue is invalid?

**Comment by gabizou** [comment]
IT's invalid for the docs, but not for the implementation.
