### ISSUE TITLE
Document World Migrator

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeDocs#431]
Currently, the docs state that CraftBukkit/Spigot worlds must be manually migrated, by copying subfolders to specific locations. However, as of Beta, SpongeForge and SpongeVanilla container a migrator which can automatically convert worlds to the proper format.

**Comment by Tzky** [comment]
How does is work? Basically you just copy the Bukkit world into the Sponge folder and upon load it's getting converted?

**Comment by Aaron1011** [comment]
@Tzky: Yes, as long as what's known as the universe name (the 'level-name' key in `server.properties`) is set to the name of the world.

**Comment by Tzky** [comment]
Ok so basically:
* copy world
* set level-name kay in ``server.properties`` to universe name
...
* Profit!

Let me try to make a PR out of this.

**Comment by Tzky** [comment]
Closing this as the discussion can continue on the PR, if necessary.
