### ISSUE TITLE
Itemstack Trade Offer API

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#434]
A new feature for handling Itemstacks & trade offers. Coming soon, and will need docs.
https://github.com/SpongePowered/SpongeAPI/pull/1032/files#r49403140

**Comment by 12AwsomeMan34** [comment]
This was recently moved from 4.0 to 5.0.

**Comment by ST-DDT** [comment]
Just a little link to the API stuff: https://github.com/SpongePowered/SpongeAPI/tree/bleeding/src/main/java/org/spongepowered/api/item/merchant
