### ISSUE TITLE
Null resources when loading from classpath in dev environment.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#438]
I too just got bit by this, we should definitely have it called out on the docs.

https://github.com/SpongePowered/SpongeCommon/issues/417

**Comment by kashike** [comment]
It should be noted that this is **not required** if you are using ForgeGradle with your project.

**Comment by Minecrell** [comment]
SpongeGradle sets this automatically for all plugins, so setting this manually is longer necessary.
