### ISSUE TITLE
Add Granite Page(s)

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#44]
(From the Forums): A few pages have already been tweaked to mention Granite, and having its' own Docs page would probably be justifiable. Where the Granite implementation diverges from the nascent Forge implementation, an explanation would be appropriate for users. 

Please bear in mind that the SpongeDocs are intended to be largely implementation-agnostic where possible. We're providing info on the Forge implementation largely because the same team are writing it and the API. We don't plan to provide large amounts of detail on other implementations. Preferably third-party implementations (such as Granite) can provide a nice friendly website of their own to help users install and use it, and we can put a link in SpongeDocs.

Please let me know if there are any further complications AzureusNation & others.

**Comment by gratimax** [comment]
@Voltasalt @AzureusNation you guys are probably most interested with this

**Comment by AzureusNation** [comment]
@BlackGoat How would you like me to start adding to the documentation?

**Comment by BlackGoat** [comment]
A place to start would be to create /source/users/granite.rst and give a basic description of the Granite implementation, where to get it, how to run it, and a link to your forums. We can link to it from index.rst. Will you need more than that? We'll have to change a few of our own pages now you have a release too (eg forge.rst). Please let me know if you spot any others that need tweaking.

**Comment by BlackGoat** [comment]
Closing this for now, as the page exists at server/getting-started/implementations/granite.rst thanks to #133. More elaboration would still be welcome.
