### ISSUE TITLE
4.0 Changes

### ISSUE THREAD

**Issue by 12AwsomeMan34** [SpongePowered/SpongeDocs#450]
This issue is to keep track of any possible docs changes that are present in API 4.0.

- [x] As mentioned in #445, the warning labels should be removed and the example should be changed to `NamedCause.source(SpawnCause)`
- [ ] #436 
- [ ] #434
- [x] [Improve pagination API](https://github.com/SpongePowered/SpongeAPI/commit/00a305d92cf5d82ef12e6a375072a32c2cf82ae7)
- [x] [Clean up Economy Account Creation](https://github.com/SpongePowered/SpongeAPI/commit/c8d57dad2aa9aba99abd6f16dd62a4b4cb024d15)
- [ ] [GameProfileCache additions](https://github.com/SpongePowered/SpongeAPI/commit/e15c5f7084871ba08013d874ea99762ad7ac45db)
- [ ] [Add ability to get/set forced bed location](https://github.com/SpongePowered/SpongeAPI/commit/2f99e6cb0c8e20c4aa9a634319fb960eb5de984b)
- [ ] [Add AssetManager](https://github.com/SpongePowered/SpongeAPI/commit/5b963664e226a63861288577281ccfd647ed0ec2)
- [ ] [Refactor tab list](https://github.com/SpongePowered/SpongeAPI/commit/5ef50f1b7b5fc1af267c93abd8ff060a9d44d502)
- [ ] [MessageEvent changes](https://github.com/SpongePowered/SpongeAPI/commit/6b09b2bcd5a57587e2a97ce7b184d7db02aa30a6)
- [x] [Make Ban reason optional](https://github.com/SpongePowered/SpongeAPI/commit/bcf61e1a316cc453f608392385942f1020e6cf5b) (Ban docs are going to be handled in the `feature/bans` branch)
- [x] [ChatType/MessageChannel additions](https://github.com/SpongePowered/SpongeAPI/commit/e1c4ac8ecc24404e99317076761e4c172ad23499)
- [x] [Pitch modulation](https://github.com/SpongePowered/SpongeAPI/commit/ea3e4e93f9c3bc8e9f77a355bc2850cd91597228) (Sound docs are in the `feature/effects` branch)
- [ ] [GameProfileProperty API](https://github.com/SpongePowered/SpongeAPI/commit/e022fc0f05df998ed5c0e371f8d65e916872c560)
- [ ] [Make CommandFlags accessible](https://github.com/SpongePowered/SpongeAPI/commit/7ecd9c9194d8799938f89c59c41d70b2287713e6) (will be handled in the `feature/flags` branch)

(List is a WIP, will update with more when I have time to go through bleeding)

NOTE that not all of these will necessarily be added to the docs when they update to 4.0.

Taken from a recent status update:
- [ ] Persistence API Rewrite: DataFormat API

If anybody knows of any more, report them below so they may be added to the list.

EDIT: Work on some of these changes has begun in the `update/4.0` branch.

**Comment by windy1** [comment]
IIRC @Zidane said he would like to have TextTemplates in by 4.0. Some docs on that could certainly come in handy. I'd be happy to help write some of them.

**Comment by Tzky** [comment]
I just bumped the Docs to 4.0.3. We can merge the first 4.0 changes now, if you're ready.

**Comment by 12AwsomeMan34** [comment]
The major 4.0 breakages have been merged to master. Some of the minor additions and what not from bleeding still need to be added to the docs, but the current docs should be fine as-is in terms of 4.0 (unless something was missed). Should I go around making issues for the new 4.0 stuff that hasn't been tackled yet and slap a help wanted sign on them?

**Comment by gabizou** [comment]
I'm not sure if it's already been done, but `Cause` usage did change a bit.

**Comment by 12AwsomeMan34** [comment]
I recently noticed, pushing a fix soon.

**Comment by Tzky** [comment]
12Aw34:

Sounds good. If you want to, go ahead and create these issues :)
