### ISSUE TITLE
Vector Copy of the SpongePowered Logo

### ISSUE THREAD

**Issue by 20zinnm** [SpongePowered/SpongeDocs#457]
I have no idea why it's not already provided, but I'd like a copy of the SpongePowered Logo for use in the Block 19 banner. Please add it to the branding page.

**Comment by Inscrutable** [comment]
They are available on the [Sponge Staff GoogleDrive](https://drive.google.com/drive/folders/0B_vQgv8p_vU2RkVvNnluR1NsLWc) so we should be able to sort out some public links shortly.

**Comment by 20zinnm** [comment]
@Inscrutable It's odd that you supply a PNG version of it but want people to retain the proportions when it makes it ridiculously pixelated. Anyways, thanks for the initiative and I'll await further information.

**Comment by gratimax** [comment]
We created a repository to hold assets because they need to be source-controlled anyway, but as soon as it is made public you should see a link to all svgs here: https://github.com/SpongePowered/SpongeAssets/tree/master/logo/svg

**Comment by Inscrutable** [comment]
I'd like to get this sorted soon, as [the demand for art assets is growing](https://www.reddit.com/r/spongeproject/comments/4btgtt/sponge_marketing_material/). We'll want to offer a vector Spongie, Icon, and Logo (with text) on the art assets page. Is there any point offering a few sizes of .png/.jpg files too? This was originally mulled over in #346

**Comment by Tzky** [comment]
Closing this as #470 will solve the issue, once pulled it.
