### ISSUE TITLE
Documentation on the AssetManager

### ISSUE THREAD

**Issue by 12AwsomeMan34** [SpongePowered/SpongeDocs#459]
Document [Assets](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/asset/Asset.java) and the [AssetManager](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/asset/AssetManager.java) and how to properly use them.

Relevant Commit(s): https://github.com/SpongePowered/SpongeAPI/commit/5b963664e226a63861288577281ccfd647ed0ec2

**Comment by windy1** [comment]
https://github.com/SpongePowered/SpongeDocs/pull/462
