### ISSUE TITLE
Documentation on the Game Profile Property API

### ISSUE THREAD

**Issue by 12AwsomeMan34** [SpongePowered/SpongeDocs#461]
Document the [GameProfileManager](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/profile/GameProfileManager.java) and what a [ProfileProperty](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/profile/property/ProfileProperty.java) is/how to use it.

Relevant Commit(s): https://github.com/SpongePowered/SpongeAPI/commit/e022fc0f05df998ed5c0e371f8d65e916872c560
Relevant PR: https://github.com/SpongePowered/SpongeAPI/pull/974

**Comment by RobertHerhold** [comment]
Resolved in 8b7f1f19b146f1900e5805594195a004e46133fa
