### ISSUE TITLE
Spawn Override Permission

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#463]
https://github.com/SpongePowered/SpongeCommon/commit/6b2e66d5fcebae2cad7ab0e0d31c0c0b40b8ab3a

Document spawn override permission.

**Comment by Inscrutable** [comment]
> Purpose: Change spawn protection to take advantage of Sponge permissions. Rather than affecting only the default world like vanilla, this will apply to any world. Additionally, fire a spawn protection event.

Adds permission ``minecraft.spawn-protection.override``

This should be straightforward. It's on _SpongeCommon_ master branch, so it's current.
