### ISSUE TITLE
Inconsistency of SpongeAPI

### ISSUE THREAD

**Issue by jamierocks** [SpongePowered/SpongeDocs#465]
It is done ```SpongeAPI``` in some parts of the documentation and as ```Sponge API``` in others

**Comment by Inscrutable** [comment]
**SpongeAPI** is the proper noun denoting the actual API that SpongePowered make. In a few cases, "the Sponge API" is used instead to refer to it more generically (in context with other APIs). If you can cite any instances where it's specifically *wrong*, please do so.

**Comment by jamierocks** [comment]
I personally think that all instances of ```Sponge API``` are wrong. :P
