### ISSUE TITLE
[WIP] Document Cause Tracking

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeDocs#469]
Currently, Cause Tracking is a system that is poorly understood outside of those who are well initiated (and even then some people don't even know how the new system works in the SpongePowered/SpongeCommon#503 PR).

To illuminate some people, not only for developers of the Sponge project as a whole, but to plugin developers and server administrators alike, I'd like to dump as much information as possible about the _new_ system in an edible documentation area.

For starters, the system works based on a recursive approach of reacting to _anything_ happening in the `Game`. Be it whether an `Entity` is ticking, or whether a `Command` ends up creating hundreds of thousands of blocks.

The core concept is as follows: "Anything that can do something, or has the potential to do something, the `WorldSErver` enders a `IPhaseState` dictating what sort of objects to expect to be created and modified. The way it works ias that before most all logic is actually casted in vanilla, this project will end up representing all sorts of mod based interactions being _trackable_ and most importantly **usable**. 

I'm sure I'll come up with more to write at a later point in time today.

**Comment by gabizou** [comment]
@SpongePowered/developers I'd like to know what you guys do not know or would like to know a certain part of it.

**Comment by Inscrutable** [comment]
Also related, Cause API: https://github.com/SpongePowered/SpongeDocs/issues/267
This really needs to get started, although someone familiar with the system has to be involved...

**Comment by ST-DDT** [comment]
@gabizou Does https://docs.spongepowered.org/stable/en/plugin/event/causes.html cover this or is anything missing?

**Comment by gabizou** [comment]
I was imagining explaining the ever evolving `PhaseTracker` in an abstract sense. But because it's implementation, I may consider just closing this as is. It's being documented better and better every time it's being refactored/improved.
