### ISSUE TITLE
Event help pages lack details on Priorities (explanations, how to use)

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeDocs#472]
Event sections refer to Priority but do not include an example anywhere of how the priority is set in the code.  Please add an example usage, outline of the priority modes.

**Comment by 12AwsomeMan34** [comment]
[It does so here.](https://docs.spongepowered.org/master/en/plugin/event/listeners.html#about-listener) Although there isn't really a code example for it. It probably wasn't included due to it being fairly standard:
`@Listener(order = Order.EARLY)`

**Comment by Inscrutable** [comment]
Including the word "Priority" in the description would help, too.

**Comment by theboomer** [comment]
Note as well then that section says "There are a few configurable fields" and just states "order"... does that mean that the other configurable fields are __that much more standard__ that they dont even need to be mentioned cause duh, they're so obvious?

**Comment by 12AwsomeMan34** [comment]
There's also `beforeModifications`, which is really just
`@Listener(beforeModifications = true)`

The javadocs for it state
`Whether this listener should be called before any other server mods, such as Forge mods. All Sponge event listeners are called after mods, unless they specify the {@link #beforeModifications()} flag to be true.`
if anyone wants to add it to the list.
