### ISSUE TITLE
PDF-version of documentation

### ISSUE THREAD

**Issue by NodonDarkEye** [SpongePowered/SpongeDocs#473]
Hello sponge community,

I noticed that there isn't a PDF version of the documentation. This could be of much help for me since I spend alot of time on public transportation without internet and i still would like to read it.
Maybe this could be interesting for other people aswell, I don't know.

Greeting Nodon Darkeye

**Comment by NodonDarkEye** [comment]
I've now gotten the spongedocs localy and just use them that way, but still a PDF version would be interesting I think

**Comment by Tzky** [comment]
I agree that having a downloadable version of the Docs in PDF format would be a great addition. 
Docs staff will consider this and also check if and how it's doable with our current buildsystem.

But please note that this is a rather low priority issue, as our main focus is to get the docs done ;)

**Comment by simon816** [comment]
Just noticed that sphinx has support for LaTeX, epub and more, https://github.com/SpongePowered/SpongeDocs/blob/master/make.bat#L116-L130
I don't know how translation files work if that's important but a PDF looks pretty doable.

**Comment by Tzky** [comment]
I investigated a bit: the LaTeX route would require a full LaTeX installation on travis. My guess is that this would lengthen the build time by a lot. 

The other option is ``rst2pdf``, however i read that the output of LaTeX looks a bit more beautiful. We'll have to try both and decide afterwards.

**Comment by Tzky** [comment]
We looked into providing a PDF as download and ultimately decided against it. It would require us to setup and maintain a fairly large dependency (LaTeX is *huge*). Instead we'll provide the Docs as *HTML zip* download. You can download the (optionally translated) docs via the lower left menu on the new theme:

![image](https://cloud.githubusercontent.com/assets/10940670/22618680/4713eebe-eae3-11e6-8281-25c4e9fde131.png)
