### ISSUE TITLE
Document Sponge Added Optimizations

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeDocs#482]
We should be documenting the optimizations, not only in the config, but also on the docs. Note that a lot of optimizations are version dependent so some of them may exist in one version, and are removed in the next.

To get started:

SpongeForge 1.8.9
- [x]  EntityActivation - Changes the activation ranges to be user configurable. These are world dependent and should work with all mod added entities.

SpongeCommon (Common for both implementations)
- [x] Lighting patch to ignore unloaded chunks
- [x] Cache chunk lookups
- [x] Reduce hash lookups on BlockState queries

SpongeCommon 1.9
- [ ] Use Wall timing for day/night cycle and common tile entity ticking (makes furnaces and the day/night cycle appear to move at wall time instead of lagging according to the server) Defaults to false
- [x] Item Drop Pre-Merging - Forces drops performed from entities and blocks to pre-emotively get merged into single itemstacks (up to the max stack size) to avoid spawning multiple entities and later requiring merging
- [ ] Eliminate a Double Chunk Load From File - Simple patch that is to be removed in 1.9.3

**Comment by Inscrutable** [comment]
The entity activation stuff is already described to some extent in the table on the [sponge.conf page](https://docs.spongepowered.org/master/en/server/getting-started/configuration/sponge-conf.html). Note: that page probably needs updating for API 4.X too ...
Are all these new optimisations configurable in the sponge.conf file(s)? 
If we do add a new page, it should probably be called _Optimisation_ and placed in server/spongineer.

**Comment by 12AwsomeMan34** [comment]
I believe I checked that page for updates and iirc it didn't need changing -> 4.0. I guess I forgot to tick the build number and version at the time of 4.0. It's been a while though, so I'll have to verify that when I get some time.

One question from myself: Were any of these optimizations present in the 4.0 release?

**Comment by gabizou** [comment]
The only optimization that I know of in the 4.0 release was entity activation. Everything else was added in 4.1+.

**Comment by Inscrutable** [comment]
After discussion with @12AwsomeMan34 , we think a new page showing off the bonus features of Sponge implementations would be a good thing. It should mention all-of-the-above (insofar as it pertains to 4.1.0 API versions), and probably deal with #502 as well. "Streamlining Sponge", perhaps? ;)

**Comment by Tzky** [comment]
Ticked of the items on the list which were resolved in #509.
