### ISSUE TITLE
Document sponge plugins reload command

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#492]
Zidane has added GameReloadEvent to SpongeAPI, and the command /sponge plugins reload. It's already been pushed to [master](https://github.com/SpongePowered/SpongeCommon/commit/5e2ce74d61345aa45aabd13affaaf967549dbb07). The docs needs to strongly encourage the use of this event (so we don't get everyone adding their own reload command).

**Comment by Tzky** [comment]
Just for clarification:

This doesn *not* reload the whole plugin but the plugins config, right?

**Comment by 12AwsomeMan34** [comment]
```
18:58:57	@Zidane	Basically you would get an event you can listen to
18:59:00	@Zidane	Do what you want in it
18:59:06	@Zidane	Sponge impl gains /sponge reload
18:59:14	@Zidane	Simply fires an event
18:59:20	@Zidane	Not what Bukkit thinks of as "reload"

19:02:20	@Zidane	Well its not just config
19:02:23	@Zidane	Its just a callback
19:02:40	@Zidane	Just a way to say "Hey plugin they executed this command, wanna do something?"
```
Also according the commit message here https://github.com/SpongePowered/SpongeAPI/commit/b81b646c3e2ebb3a24ab2253f27398814b475834, it's up to the plugin as to what gets reloaded with it, config or otherwise.

**Comment by Zidane** [comment]
As an amendum to the above, its now /sponge plugins reload

**Comment by ryantheleach** [comment]
By default, it does nothing. Plugins can choose to act on it if they wish.

**Comment by Inscrutable** [comment]
This will get a mention on the server commands page soon, but more importantly it needs a mention somewhere in the plugin development section. Does it justify a new page, or can it be tacked onto an existing one?

**Comment by Zidane** [comment]
No reason for a new page as its just a way to call an event with a contract assumption that one performs a "reload" in it :).

**Comment by Inscrutable** [comment]
In the commit, it looks like the permission for it (and the description) is the same as /sponge plugins. This may prove a problem for server owners who'd like to let players see the plugins list but not execute reload....

**Comment by Inscrutable** [comment]
This is due some minor perm changes, possibly to ``sponge.plugins.reload`` (or more logically, it could just share ``sponge.command.reload``, or be a subsidiary node of that).

**Comment by simon816** [comment]
The permission was fixed and changed to `sponge.command.plugins.reload`
https://github.com/SpongePowered/SpongeCommon/commit/0eccbc74272f473b07aec1788a3ad072bc3618f0

**Comment by Inscrutable** [comment]
Yeah, I'm aware of that @simon816 - I was talking to Zidane yersterday, and further changes were proposed. Technically ``sponge.command.plugins.reload`` is a parent of ``sponge.command.plugins``, and would get included unless specifically denied. If nothing happens, I'll go with ``sponge.command.plugins.reload``.

**Comment by Inscrutable** [comment]
OK, unless anything else changes, all this needs is a mention in the plugin/events hierarchy (perhaps the index) to reminds folks that it's there and please use it.

**Comment by 12AwsomeMan34** [comment]
The plugin side of this new command has been handled in https://github.com/SpongePowered/SpongeDocs/commit/fd747227ce007a82ecc7a9957dbc1f653d87d58b.
