### ISSUE TITLE
4.1.0 / 5.0 Checklist

### ISSUE THREAD

**Issue by 12AwsomeMan34** [SpongePowered/SpongeDocs#493]
5.0 (might) still be a ways off yet, but that doesn't mean we could do without another checklist!
This issue is to keep track of any possible docs changes that are present in API 5.0.

I'll be using the compare diff from `release-4.0.0` branch to `bleeding` to see the changes:
https://github.com/SpongePowered/SpongeAPI/compare/release-4.0.0...bleeding

Stuff that's strike-through is stuff that will not be covered at this point in time or will not necessarily be covered in the near future.

| :ballot_box_with_check: | Commit / URL | Notes |
| --- | --- | --- |
| <ul><li>[ ] </li></ul> | [SpongeDocs 5.0 Milestone](https://github.com/SpongePowered/SpongeDocs/milestones/v5.0.0) | Stuff that's labeled for 5.0 on docs |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/7d1f7c0ae9f343012d1796d9c83c22cf86057721 | Start work on some passenger related updates. Dunno if this is mentioned in the docs, just keeping here to keep track. |
| <ul><li>[x] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/8c14fedc2e1176fdf611f1dddf73025e165acfda | Server not always available. Should be noted somewhere. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/6c0040bf4ee5e22b5be4c8c36ffdf4ada373d1df | Goodbye target task. For anyone planning to do AI docs, keep this change in mind. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/603c762ce955977251fd8ae01565ea30f69ea29e | Remove suspended data. Make sure this isn't used anywhere. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/a216a72f2a23cf78e6bd729f94ed53e7d42e255a | SoundCategory can now be used when playing a sound. NOTE [this](https://github.com/SpongePowered/SpongeAPI/commit/740974c4ba193b8ed689fdd459e23504dc25fa2b) change, [this](https://github.com/SpongePowered/SpongeAPI/commit/185fd4baabe383e2f8c7a7288c3ea27c9be56f26) change, and other changes to those files too. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/5ffa7f69c33a302a757e99f06449ded5eb8547d0 | Splash potions are no longer data. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/3f933164ae540d14610e2bb140fb109794413847 | Passenger -> Passengers |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/12aae1df2d48b1d2aef9f7f453ebbd24d1e6ae38 | Fix misnamed/misplaced catalog types. Should go through and make sure current docs don't contain these 'misspellings'. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/654f676f6aec2a813885565656a34589883a9c30 | Detach LocatedSource from CommandSource heirarchy |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/05f994d81383594b6e9d21f0acc9f0ed8561e1ca | Use Locatable where possible. Need to go through an update any necessary methods accordingly. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/7d936e4b2dbf7c2c7ecf2b0ef1713dce5484e795 | Rework explosives API. Maybe add explosives + explosions docs? |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/cb24adf3921ce785d52bbb549c2c375c1d4ac5f7 | MainHand/Offhand to interact events |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/76d1a71c6b00646065ce3105f5a9b3edaba79f86 | Remove Entity safety methods. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/bacd993453ac39e3ed3f78007bbce42ff08f665c | Rename DisplaceEntityEvent to MoveEntityEvent |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/3914b07899b2fa70ea8c42727c98a9935f8b12dd | More move event stuff |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/11bcb9f551ce52c6eb88bc5d8403778e1434b0fa | Even more Move event changes |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/bace84e131b8f1a79e1770d5ba191c2e0b5514d7 | Remove EntitySnapshot from SpawnCauses, should only use Entities. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/4a4f5aa3cc8487a52e56d09f6f51d0619f0467ec | Boss Bar API |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/14fab8a1a9c8cb13b964814028e9bda949224d53 | Add target location parameter to tab completion |

World stuffs get their own section. I do know there are significant world changes in 5.0, and I believe somebody else wanted to help us out with that. I'll be honest and say I have no idea what world changes will be relevant to docs 5.0.

| :ballot_box_with_check: | Commit / URL | Notes |
| --- | --- | --- |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/2a547758a02cbf0cb5a3ee2874a2980252865cf9 | Add populators for new end generation. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/2738e869310a614c0052e0173032fec8b31d0875 | Removed EnderCrystalPlatform populator |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/4604c376849acf64d5eb6f3bab05873a7a2fbc87 | Remove setters on dimension methods. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/bf37bce50e5e7a16a2a438a37b395894d795daaa | Exclusion radius! |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/0ff9dda6c7932c04cc04437f1bd2124779d99531 | Remove redundant methods + rename. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/7349b47cced0d9217b213b8fc20b862a37935a8a | Pre/Post events on WorldSave |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/edcf25c48f8404524b2f0a29580f937ae1fea026 | Require World beforehand in transferToWorld |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/f36d1fe21ca88df54d9b34be7266076a9cd594a3 | Remove world (folder) name from WorldCreationSettings and catalog it. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/b2478b3d6f5414a9803e6e148481d2ef962427ad | Cleanup World interface. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/0fb9e04d0fc9e0f3b984aa794d13d78e8a77a40d | Remove worldName from WorldCreationSettings builder, require id and catalog name for building. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/f19ebc6034dc0ac931d08b6ec028b973f2518732 | Cleanup WorldCreationSettings docs, add generateBonusChest to Builder. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/486d3bcba4ad6faf735cea98aa548405cfc53ab4 | Add commandsAllowed to the WorldCreationSettingsBuilder. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/669f84a77187d1a4932014155e10a945567d67ee | Add SerializationMode which lets a dev configure how Worlds save region data. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/fb8ef2fef94f436c2d82c490cdc133277f33e0df | Rename to SerializationBehavior and change constant names to fit better. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/a0c60337e314fed195a21552a443d39d4fc8c2ed | Adds save() to World. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/3172beb396c03a9e7344c40e097fa66b139c5c58 | Expose the bonus chest setting from WorldProperties. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/ea70eb75512d7fe023376f89216297913ba48920 | Allow setting difficulty in the Builder for the WorldCreationSettings. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/6974ae183a8d9b422b2c55985d38637e1b7269db | Allow creation of WorldCreationSettings from Properties. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/dc32cb17d5b3047db351f21220b8e8397e212699 | Have register in GameRegistry return Catalog being registered. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/2230fa60767aae44243d2d19913a2b5d351b4b53 | Rename WorldCreationSettings to WorldArchetype to better explain its use. |

4.1.0 changes are getting their own special section!

| :ballot_box_with_check: | Commit / URL | Notes |
| --- | --- | --- |
| <ul><li>[x] </li></ul> | [SpongeDocs 4.1.0 Milestone](https://github.com/SpongePowered/SpongeDocs/milestones/v4.1.0) | Stuff that's labeled for 4.1.0 on docs |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/4c8411aa9b9d819a20eb9f8a3691b031f07829ba | Add Asset.readLines(). Does this belong in asset docs? |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/e656bf9153719e62d5a191d73bf58cae272eaca1 | Add DataView#getCatalogType support and introduce AbstractDataBuilder. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/7e9670daf2d366ea0ba641095131084a1a8220c2 | Explosion#shouldDamageEntities. Perhaps add explosion docs? |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/de17e561d6c20596999bd7794c7a32b934910388 | Methods to create TextFormat. |
| <ul><li>[x] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/74497573db02979ddc3a5d827098ef807a0c9551 | Book view API. Seems neat. |
| <ul><li>[x] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/13824807be7ed6982cb7c14209c57047166c0d64 | Virtual block change API. Also seems neat. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/2ce0832dfb7dcf65addf4da0a887fb56c58aef0d | DataSerializer API stuffz |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/def7d57045e377ac25d4cac8fe96b1892fc1ab49 | BlockSnapshot.None + Interact block secondary changes |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/ee405ed4cdc4fcf5e384e8682e6eb19dfa278309 | Add AttackEntityEvent |
| <ul><li>[x] </li></ul> | ~~https://github.com/SpongePowered/SpongeAPI/commit/c0e27ed0a3b217e43088776af822b6c23db13b11~~ | ~~Chunk#getNeighbor API~~ |
| <ul><li>[x] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/4d69a8187ee74205b5f894a1ffe3e4ceed1307fd | Getter parameter source field |
| <ul><li>[x] </li></ul> | ~~https://github.com/SpongePowered/SpongeAPI/commit/8c015f860d8444bad2613423f7c4e7e46c79c352~~ | ~~New methods to ChannelBuf.~~ |
| <ul><li>[x] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/e512e9f329f16a7796779d0bf2168a5be06f8403 | Expose ItemStack equality method |
| <ul><li>[x] </li></ul> | ~~https://github.com/SpongePowered/SpongeAPI/commit/b9b5365a2fe8ca16745544c40ecda620d36a41d7~~ | ~~Add utlity methods to get all catalog types for a plugin.~~ |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/3cfe88afb4e40165244833d9f9c2d5e52cbeb00c | TeleporterAgent -> PortalAgent |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/b17b38bbf1a5a894a15819db6646904e5208a3d4 | Builders for TeleportCauses |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/90c0996190683e7d5b62ff695918073fc7536222 | Fix Portal not being nested under Teleport in DisplaceEntityEvent. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/29eeb92d962fc5c09439f296ed1d5533094d0686 | Change setLocation return type to boolean. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/bd51b3af2e524b4487881c022a6b191d99451986 | GameProfileCache methods. |
| <ul><li>[ ] </li></ul> | https://github.com/SpongePowered/SpongeAPI/commit/c988e70a7a5c62e66fa607e6b63e4766bc34ac15 | CommandManager#getOwner |

I'll hopefully update the list as more stuff comes out, but there's no guarantee that I'll be immediate in that regard.

Note that not everything in the list is a must-do for the docs. It's simply to keep track of changes which _may_ be in the docs or perhaps may need to be noted. Not everything off of that checklist will necessarily be in the docs at a future/current time.

Work has currently begun in the `update/4.1` branch. Follow developments there.

**Comment by Zidane** [comment]
@12AwsomeMan34 

WorldCreationSettings is now WorldArchetype. You now must pass a WorldProperties to WorldArchetype.builder().from() to build a WorldArchetype from WorldProperties.

Basically WorldArchetype is a blueprint FOR a World itself and is a CatalogType in API 5.

Lemme know if you need other things explained. There are more API breaks to come.

**Comment by gabizou** [comment]
I am somewhat of the opinion that some differentiation should be made as to what API was added in 4.1 versus 5.0. I notice that some of the API additions mentioned are actually added in 4.1-SNAPSHOT.

**Comment by Tzky** [comment]
We can bump the Docs to 4.1 and add all 4.x changes to it, if you want us to. Usually we try to stick to full releases on the Docs, that's why we're still on 4.0.3.

**Comment by 12AwsomeMan34** [comment]
Yeah, this is largely a general update list. I could go through those and see which ones are on master for a proper differentiation on 4.1 vs 5.0.

**Comment by Inscrutable** [comment]
This probably needs going over for relevance. API 6.0 is on the horizon...

**Comment by Inscrutable** [comment]
... aaaaaaand API 6.0 is here. We definitely need to review this list.

**Comment by Inscrutable** [comment]
This needs resurrection for API 7 or a decent burial. Should we close this and move on @12AwsomeMan34 ?

**Comment by 12awsomeman34** [comment]
I meant to close this after seeing your comment, oops.

Yeah this is pretty old stuff and a new sweep of the docs is probably needed to check for outdated-ness.
