### ISSUE TITLE
Mob Spawn Range feature

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#497]
Mob-spawn-range was recently added to the World config file, in the worlds section, with a helpful description. In short, it simply lets you configure the range in which mobs spawn around a player. Lower values = mobs spawn densely near you; Higher values = mob spawns are more spread out. This value is CAPPED to your server's view distance.

**Comment by 12AwsomeMan34** [comment]
As per the (so far) usual, I'll handle this along with the global.conf file update.

**Comment by 12AwsomeMan34** [comment]
Covered in #498.
