### ISSUE TITLE
Mixins for plugins?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#50]
Are mixins actually going to be exposed to sponge plugins? or should that section be moved to the section on developing for the sponge implementation?

**Comment by progwml6** [comment]
mixins will not be exposed to plugins

**Comment by simon816** [comment]
It should be moved to `devs/forge/contributing` section

**Comment by BlackGoat** [comment]
Moved to devs/forge folder, which probably needs its' own index page as it grows.
