### ISSUE TITLE
Show off Hovertext and tab-completion

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#502]
There are some nifty features provided by the Sponge implementations (SV and SF) that make things easy for users and admins. For example, the `/sponge plugins` command provides a list of plugins in-game that will reveal their version when Hovering over the name.
Similarly, tab auto-completion works reasonably well with `/sponge` commands, in-game and via console. 
I didn't see any reference to these ease-of-use features in the docs, and I think they're worth mentioning. This would apply to the 3.1.0 docs branch as well as current.

**Comment by Mumfrey** [comment]
I preferred your original issue title.

**Comment by 12AwsomeMan34** [comment]
`TextActions` are mentioned [here](https://docs.spongepowered.org/master/en/plugin/text/text.html#example-text-with-an-action), and they can [show text](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/action/TextActions.java#L111) to the client when hovered.

I believe tab-completion on commands is automatic, unless you use [CommandCallable](https://docs.spongepowered.org/master/en/plugin/commands/commandcallable.html), which has a `getSuggestions()` method for the arguments.

**Comment by ryantheleach** [comment]
I think inscrutable was talking about in the admin/user pages, not the dev pages.

**Comment by Inscrutable** [comment]
Yeah, this is all bragging rights for user-facing pages, as these are just ease-of-use features. They're pretty neat, and yet not mentioned in our docs. Whilst vanilla MC does have some hover stuff, it doesn't have plugins to have versions.
As for tab-completion, not all plugins (or mods) do a good job (eg PEX), but Sponge does it well imho.

**Comment by ST-DDT** [comment]
I'm really not sure where we could add this show off image.
Maybe we should place it right below the [Server - Spongineer - Commands # Sponge](https://docs.spongepowered.org/master/en/server/spongineer/commands.html#sponge) table.

Maybe something similar to this:

> ![spongepluginscommandshowoff](https://cloud.githubusercontent.com/assets/1579362/21355883/f5a9b82e-c6cf-11e6-9d50-d1c923ae62e0.png)
>
> Red box: The result of the `/sponge plugins` command.
>
> The elements in that list can be hovered to show their version numbers (see green box).
> Also when clicking a plugin detailed information will be shown for the given plugin (see turquoise box). The additional information can also be shown be sending the `/sponge plugins <PluginId>` command. If you are not sure about the plugin id or other subcommands you can try the tab-autocompletion.

Would this be enough to solve this issue or would you like to add more stuff or add it to its own page as mentioned in #482 .

**Comment by Inscrutable** [comment]
That does cover most of the bases, although it's a bit scanty on autocompletion. Adding "Sponge commands provide detailed tab-autocompletion, as do many plugins." or similar might do the trick.
The image is a good idea; it reduces the amount of text needed to describe the features, although it (and the body text) could probably use a little polishing. 
I concur it's probably most appropriate on the Spongineer Commands page, and we can detail the actual under-the-hood optimisations elsewhere.
