### ISSUE TITLE
Document world border changes

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#505]
https://github.com/SpongePowered/SpongeForge/issues/650

Sponge separates out the world borders so they can work with multiple worlds. As a side effect this probably affects the nether and end.

**Comment by Inscrutable** [comment]
OK. Does setting one in the _overworld_ also set a corresponding one in the _nether_ and the _end_? Default vanilla behaviour is ``The world border's dimensions and location are the same across all three dimensions``.
We should probably include some examples when we document this.

**Comment by ryantheleach** [comment]
I don't know.

**Comment by gabizou** [comment]
@Zidane can answer!

**Comment by Zidane** [comment]
The worldborder command now affects only the world you execute it in.

I'll likely roll that change back and have it affect all worlds by default. Then with the Multi-World commands PR, you can toggle on per world commands as you please.

**Comment by Inscrutable** [comment]
What's the present status of this @ryantheleach ? It should be easy enough to document as a ``note`` on the *commands* page.

**Comment by ST-DDT** [comment]
Whats the current status on this? Does the world border command currently affect all worlds or only one? And are changes to that behavior expected to be soon? Does this behave differently if executed by the console?

AFAICT it does affect all worlds (See [`MixinCommandWorldBorder`](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/command/vanilla/MixinCommandWorldBorder.java)) so is this issue still relevant?

Should we add a comment/note like this to the command?

> Please note that this command sets the worldborder for all worlds at the same time. Multi-world plugins will probably provide their own command to set the border on a per world basis.

**Comment by ST-DDT** [comment]
@ryantheleach Do you mind if I take over this issue?

**Comment by ST-DDT** [comment]
There are also config options related to this:
````groovy
multi-world-patches {
	defaultgamemode=true
	difficulty=true
	gamerule=true
	seed=true
	setdefaultspawnpoint=true
	time=true
	toggledownfall=true
	weather=true
	worldborder=true
}
````
https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html?highlight=multi-world-patches

**Comment by ryantheleach** [comment]
Go for it.
