### ISSUE TITLE
GameReloadEvent trigger command

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeDocs#508]
The command `/sponge plugins reload`([here](https://docs.spongepowered.org/master/en/server/spongineer/commands.html#sponge)) should be mentioned or linked in [this document](https://docs.spongepowered.org/master/en/plugin/event/listeners.html#gamereloadevent). I searched a bit to find how to actually test if my plugin does react on the GameReloadEvent.

**Comment by 12AwsomeMan34** [comment]
Yeah, that's probably a good idea. :P Sorry for the trouble it cause ye.
