### ISSUE TITLE
[minor] Asset API

### ISSUE THREAD

**Issue by 20zinnm** [SpongePowered/SpongeDocs#514]
`Asset asset = plugin.getAsset("myfile.txt");` and `Asset asset = Sponge.getAssetManager().getAsset(plugin, "myfile.txt");` both return `Optional<Asset>` while the docs make it seem as though it's a straight reference, returning `Asset`.

**Comment by 12AwsomeMan34** [comment]
Yep. I'll likely fix it with #511, as that already has a few fixes for parts of the docs anyway.

**Comment by 12AwsomeMan34** [comment]
Should be resolved as of https://github.com/SpongePowered/SpongeDocs/pull/511/commits/151d688b440b64f9d24e13b32b20ecac2665bfb9 and in the docs when #511 is pulled.
