### ISSUE TITLE
Basic documentation of UserStorageService

### ISSUE THREAD

**Issue by MarkL4YG** [SpongePowered/SpongeDocs#518]
I recently wrote a plugin that disconnects users without a certain permission on join.
Since the ClientConnectionEvent.Join wouldn't let me kick a player without something crashing on me I used .Auth instead.
Since this event is very early, a Player instance is not yet available thus one needs to use  the UserStorageService.

---

**_The thing is**_: There's no clue that this service exists and can be used to easily access offline player data and do things like checks for permissions.
This results in hours spent on google trying to figure out how to access offline data.
I now would like to suggest creating at least a basic documentation telling new devs about it's existence and basic usage.

My suggestion would be somewhere near the doc about the Game Profile Manager since I can imagine cases where these two could be used together.

Also:
I would create that doc myself but since I'm new to contributions to sponge I would like to discuss about this with _more experienced_ people :)

**Comment by Inscrutable** [comment]
We would be absolutely delighted to see what you can offer as a PR. If you throw something in our direction, I'm sure our staff and a few roaming devs will review it and comment as required. It doesn't have to be perfect, just be familiar with our Style Guide (it's on the docs!) and show us what you can do.
Go on, jump in and get your feet wet!

**Comment by Meronat** [comment]
@Inscrutable This can be closed with https://github.com/SpongePowered/SpongeDocs/pull/519

**Comment by MarkL4YG** [comment]
How didn't this ^^''
