### ISSUE TITLE
Forge Version to SpongeForge Version Chart

### ISSUE THREAD

**Issue by 20zinnm** [SpongePowered/SpongeDocs#521]
In the IRC channel, we get a lot of "bugs" that are usually resolved by switching either Forge or SpongeForge versions. It'd be nice to have a chart with the latest build number that works on any given Forge version; this might need to be auto-generated. I feel like a CI could do this.

**Comment by RobertHerhold** [comment]
There is already a page on the docs explaining how to pick the appropriate version of Forge based on your build of SpongeForge...

**Comment by 20zinnm** [comment]
Oh, there is? Could we update khobbit's Lain with a .forgeversion or something?

**Comment by RobertHerhold** [comment]
The page in question is [here](https://docs.spongepowered.org/master/en/server/getting-started/implementations/spongeforge.html).

**Comment by Tzky** [comment]
Afaik that page doesn't explain API version to plugin versioning. But there definitely is a page that tells users to always match versions as using different versions will usually lead to issues.
