### ISSUE TITLE
Configuration Loaders (loading default config) outdated

### ISSUE THREAD

**Issue by 20zinnm** [SpongePowered/SpongeDocs#522]
On the Configuration Loaders page, the loading a default configuration section is outdated. It can be found [here](https://docs.spongepowered.org/master/en/plugin/configuration/loaders.html#example-loading-a-default-config-from-the-plugin-jar-file).

This is outdated in favor of the Assets API.

**Comment by 12AwsomeMan34** [comment]
For reference https://github.com/SpongePowered/SpongeDocs/pull/439#discussion_r55923342.

**Comment by ImMorpheus** [comment]
Fixed a long time ago by https://github.com/SpongePowered/SpongeDocs/commit/688b03f7272bc63b8a1d206572f84214442361df
