### ISSUE TITLE
Ore help / API information

### ISSUE THREAD

**Issue by windy1** [SpongePowered/SpongeDocs#523]
With Ore nearing Beta, I think it's time we start some of the documentation for Ore. Namely we need a help page (mainly for creating a new project from building your project to publishing it) and a API documentation page. If someone would like to start on these that would be great and I can answer any questions anyone on the docs team may have.

For reference, here are all the current API routes available: https://github.com/SpongePowered/Ore/blob/master/conf/routes#L14-L31

**Comment by Inscrutable** [comment]
Excellent. For reference, this also covers issue #8 - the oldest live issue on the SpongeDocs repo.
The help page will need basic instructions for uploaders (devs) and downloaders (users). This will also need some expanded rules/guidelines for use of Ore, so I hope @mbax can add some specifics. 
We won't make the page *live* until you give us the nod that Ore is ready for the big-time.

**Comment by kinggoesgaming** [comment]
@Inscrutable I am working on a 3rd commandline java program for ore.. I can document the API parts as I get it through

**Comment by windy1** [comment]
OK -- this is practically completed. The only things remaining is the "Support" page and the "Terms of Service" page. I didn't complete these because I'm not sure how we would like to setup our support system for users and I'm still awaiting the much anticipated ToS ;) 

Officially seeking input so we can wrap this up ASAP.

**Comment by Inscrutable** [comment]
Is there any progress a ToS and/or Support page @windy1 ? Editorial staff can help throw it together when we have a final ToS.
