### ISSUE TITLE
Minor typo in Plugin Metadata example

### ISSUE THREAD

**Issue by varrix** [SpongePowered/SpongeDocs#524]
This is a minor typo in the code example for Plugin Metadata for Sponge. 
Picture of said page at the time:
![02e8e801d3c940bcae63ef7233baf383](https://cloud.githubusercontent.com/assets/2670212/17586936/e3707d4a-5f92-11e6-83fa-c7624d2dfad0.png)

URL: https://docs.spongepowered.org/master/en/plugin/plugin-meta.html

**Comment by 12AwsomeMan34** [comment]
Uhh, no. It's closing the opening ( from `@Plugin`. Also, report minor typos to the OCD issue.

**Comment by varrix** [comment]
Oh, hah! Thanks, my bad xD
