### ISSUE TITLE
Versioning info for Contributing is out of date

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#537]
The page refers to the entirely phantasmal `release` branch. The target has also shifted: From hereon, all active development should target the bleeding branch. If it is a backwards compatible bug-fix then we will handle cherry-picking it to previously supported versions once it is merged to bleeding.
The whole page could use a review to ensure it's still in line with current practice.

https://github.com/SpongePowered/SpongeDocs/blob/master/source/contributing/versioning.rst

**Comment by Tzky** [comment]
Ok, so if i got this right, Sponge development is currently happening as follows:
* all new additions target ``bleeding``, next *major* version development happens here
* ``master`` holds the current release and possibly next *minor* version
* ``release/x.y.z`` branches are no longer in use

**Comment by Deamon5550** [comment]
Master is going to go away I think, I'll write this up once we've settled on our plan.

**Comment by ZephireNZ** [comment]
Seeing as it's not been written up, this is the plan as I understand it:

- all new additions target `bleeding`. *Major* releases will be done from this branch.
- `stable-x(.x.x)` holds the stable release version(s). Changes that are non-breaking and that are sufficiently tested in the `bleeding` branch will be cherry-picked here. *Minor* releases will be done from this branch. Potentially allows for "across-the-board" bug fixes for all server versions in the future.
- API releases will tagged when they have an official release, but impl versions should always target most recent relevant API build.

Did I miss anything @Deamon5550?

**Comment by Deamon5550** [comment]
@ZephireNZ yeah that looks good, sorry I overlooked this.
