### ISSUE TITLE
NEVER Store direct references to entities in Sets/Maps in plugins

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#541]
Referring to [this important PSA](https://forums.spongepowered.org/t/do-not-store-player-entity-references-in-maps-sets-directly/15513) we need to document this to prevent plugins causing memory leaks. This could get a mention in "Best Practices" and/or a relevant Data page.

> <blood_> https://github.com/SpongePowered/SpongeAPI/commit/167fe7b185bdba8e4addb4ced27d72c60da84c42
> <blood_> this needs to be documented
> <blood_> more info can be found here
> <blood_> https://forums.spongepowered.org/t/do-not-store-player-entity-references-in-maps-sets-directly/15513/10
> <blood_> as well as my respective commits
> <blood_> We now do exactly what Vanilla/Forge do on respawns
> <blood_> and this fixes major compatibility issues with a bunch of mods

**Comment by ryantheleach** [comment]
It's not just sets/maps btw, it was just the dumb example I happened to give at the time.

Really any references to players should be looked at carefully to make sure they leave scope.
It's just that it most commonly goes out of control in Collections.
