### ISSUE TITLE
Add documentation for creating a plugin with Minecraft Dev

### ISSUE THREAD

**Issue by DemonWav** [SpongePowered/SpongeDocs#550]
Using Minecraft Dev for IntelliJ is the easiest way to get a Sponge plugin development setup, whether it's for Maven or Gradle. I may be biased, but I think most people would agree with me there. :smile: 

It would be nice, and I would greatly appreciate it, if the Sponge Docs would at least mention my plugin, as that would lead more people to using it. So yeah, this is a selfish request.

Info on how to create a project (SpongeForge mod in this case, can be easily generalized down to Sponge) can be viewed here. https://minecraftdev.org/docs/create.html

**Comment by gabizou** [comment]
As a user of the plugin, I wholeheartedly accept this to be added to the docs.

**Comment by Inscrutable** [comment]
If it's that useful a core utility, then we could even support a page for it. That would have the bonus of providing translations that aren't available on your own Docs. I'd appreciate some opinions on where this would be inserted, and which docs pages should refer to _Minecraft Dev for Intellij_ in general.

**Comment by Tzky** [comment]
As it's a plugin for IntelliJ IDEA, i'd add on the IntelliJ page:
https://github.com/SpongePowered/SpongeDocs/blob/master/source/plugin/workspace/idea.rst

**Comment by parlough** [comment]
I'm not ready to take this up just yet, but I agree with Tzky on including some basic snippets on the IntelliJ page, but possibly having its own major category under "Ore Documentation" called "MinecraftDev Documentation" would make sense. The is useful for others beyond just plugin developers, especially for those developing with Mixin or with Sponge itself.

If anyone takes this up, know you can ask for help with the plugin or for explanation of its features in Sponge irc/Discord or MinecraftDev's irc/Discord.

**Comment by Inscrutable** [comment]
As a first pass, just adding a reference to the Minecraft Dev docs on the IntelliJ page ("this is nifty") would suffice. Later, we can make our own general page for it, and link that internally where needed.

**Comment by uglycoyote** [comment]
Having it obvious in the IntelliJ setup docs that this template plugin exists absolutely would have saved me hours of head scratching time.

**Comment by uglycoyote** [comment]
I'm improving this in #725 so maybe this issue can be closed if that pull request is accepted.

**Comment by ST-DDT** [comment]
Closed via #725
