### ISSUE TITLE
Handing over Spongy user, still hosted on github?

### ISSUE THREAD

**Issue by maxov** [SpongePowered/SpongeDocs#557]
I'm wondering if the Sponge documentation is still hosted on GitHub. The reason this is a problem is that GitHub sends me warning emails related to the fact that docs-origin.spongepowered.org is set as an A record (to fastly, I think) every time the docs are updated. There's a few ways to fix this:
1. if the Sponge documentation is not hosted on GitHub (I remember talking about this with @lukegb a while back), I or someone else can make a PR to take out the bash script that deploys the docs to GitHub.
2. I can transfer the email of the Spongy user to an active contributor (this has to be an email different from your Github account though, GitHub doesn't allow duplicates otherwise).

Thanks!

**Comment by Inscrutable** [comment]
Welcome back, o great architect! I hope you've been having a merry time in the wider universe beyond the veil of Sponge. Seasons yadda yadda and so on :)
I'll accept the Spongy email if you want to pass it on. I can share it with some of our other admin staff (and internal docs) to make sure it isn't unattended.
I'll let our web-team rise to the challenge of explaining the current SpongeDocs hosting arrangements (cue @Tzky and/or @progwml6 ). Changes are already in the wind, so we may be able to co-ordinate the efforts.

**Comment by maxov** [comment]
Hi @Inscrutable, happy holidays! Sorry if I wasn't clear: the current Spongy email is an alias pointing to an email on the lapis.blue domain. I think it would be ideal to add a new email alias with Sponge's system, like spongy@spongepowered.org.

**Comment by Inscrutable** [comment]
OK, I see what you mean. That's probably going to need assistance from @lukegb to sort out.

**Comment by Tzky** [comment]
Long time no see, so welcome back!

Our hosting solution hasn't had any major changes since you established it. We're currently still hosting the docs on github. :)

**Comment by gabizou** [comment]
@Zidane Since you're able to add new emails, could do that.

**Comment by Inscrutable** [comment]
The GitHub account has temporarily been transferred to an email @Minecrell also has access to. The Spongie _Crowdin_ account will also be dealt with shortly.
It would be preferable to transfer the GitHub account to a @spongepowered.org mail, so this issue can stay until that is resolved.

**Comment by Inscrutable** [comment]
Bump. When you return, can you tell us the status of this issue @Minecrell ?

**Comment by Minecrell** [comment]
@Inscrutable No news from my side. I'm still waiting for someone to create an email I can use for the account. We also need a secure place to store the password for the account.

**Comment by Inscrutable** [comment]
OK. @lukegb can you please arrange a nice comfy account for Spongy to reside in, and we can sort out passwords and storage/sharing as needed (GDoc or otherwise).

**Comment by progwml6** [comment]
luke and I don't run the email server @zidane does

**Comment by Inscrutable** [comment]
Is this still unresolved @Minecrell ? If so I can bring it up at SPAM next weekend.

**Comment by stephan-gh** [comment]
@Inscrutable Yes, I still need an email address and a secure place to store the passwords of the "Sponge" Crowdin account and the @Spongy GitHub account.

**Comment by Inscrutable** [comment]
I believe this has finally been resolved. Contact me or Zidane if there are any further problems.
