### ISSUE TITLE
Relicensing of the Docs

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#565]
@Minecrell raised a longstanding issue:

The docs are missing a proper license currently. I want to use this issue to discuss possible licenses and everything that needs to be done to get the docs relicensed. We also need to get consent by every contributor to relicense the docs repo, just like Forge did it.

The current plan is as follows:

* Code on Docs repo: MIT
* Assets:  [CC BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/) with exemptions (currently stated on the docs)
* Docs content: [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)

Example consent message:
> I, [developer name] [GitHub email] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA)

Pinging @Mumfrey, @Owexz, @gabizou and @Zidane for their opinion and approval.

**Comment by Inscrutable** [comment]
The License must feature in the contribution guidelines for the Docs in future, implicit agreement with whichever license applies is a necessity. The highly permissive Creative Commons BY license requires only attribution, and its very much in line with what our contributors would expect.
I am a bit surprised that SpongeDocs hadn't fallen under the envelope of our existing (MIT) License, but I can't find anywhere that explicitly includes it in the scope. If we have to contact everyone, that's going to be quite the task, as some former editors are long gone.
We also have to deal with our Art Assets in #470 , including an explicit license for them - **CC-NC/ND** seems likely (Non Commercial No Derivatives).

**Comment by ST-DDT** [comment]
How was this missed? You are right this needs to be fixed.

As for the how...
We have to get the username of every comitter and mention them here or elsewhere.
And request a post like 'i agrre to the license change' or 'i sign off my contributions'.
If this does not lead to total coverage when could then try to use the email addresses from the commits itself to try to contact the remaining people. If that does not help either we have to remove the entire page that was created with that guys help. (I hope this is legally sufficient).

PS: I agree to the license change to MIT/CC BY/CC NC+ND for previous, current and future contributions to this SpongeDocs repository. Unless stated otherwise.

**Comment by Tzky** [comment]
We relicensed SpongeHome in the past (https://github.com/SpongePowered/SpongeHome/pull/83). I'd like to do it like this for the docs, so:

1. we choose a license for:
    a) code
    b) assets
    c) docs content
2. we get a list of all current contributors, excluding past contributors and grammar correntions/typos
3. we ask everyone on the list for consent/approval
4....
5. Profit!

**Comment by Inscrutable** [comment]
Addressing (1): Licensing for code should probably be MIT to match the rest of our repos. The Art Assets need to be Creative commons CC-BY-ND-NC, with specific exemptions (as listed on the Docs now), and the docs content can probably safely be the permissive CC-BY (or if we want it to persist as CC when forked, we can use the share-alike, CC-BY-SA)
Sometime soon we will put a list up (probably as a table in this thread) with a list of contributors, explicitly asking for consent to the new license(s), via a provided Template.

**Comment by Tzky** [comment]
Agreed. I'd also go with:
* Code: MIT
* Assets: CC-BY-ND-NC with exemptions
* Docs content: CC-BY-SA

**Comment by Minecrell** [comment]
#560 moves almost all code to https://github.com/SpongePowered/sponge-docs-theme, so we can just put the complete SpongeDocs repo under the CC-BY-SA license (except the assets)

**Comment by ST-DDT** [comment]
We collected a list of all contributors, so at least that step is covered.

**Comment by ryantheleach** [comment]
I'm happy to contribute my contributions under any future license that the maintainers of SpongeDocs decide.

What's next, creating a ticket proposing the changes and pinging everyone involved?

**Comment by Inscrutable** [comment]
Pretty much, yes. We're just waiting on one of the Sponge Leaders to give the nod to the licensing. After that, everyone gets pinged by our giant checklist, and we await replies. It probably belongs on a fresh PR to add mention of the new license in the Contributing section, so future contributors will be aware of it. We can't amend the license until it's agreed anyway.

**Comment by RobertHerhold** [comment]
Likewise, I agree to any license change

**Comment by jamierocks** [comment]
May want to take a look at the GPL Free Documentation License

**Comment by Inscrutable** [comment]
We've pretty much decided the license, which happens to be the same one used by Wikipedia. It does not need a lot of detail beyond preserving attributions and keeping it public.
