### ISSUE TITLE
Best Practices incorrectly states that plugins cannot use mixins

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeDocs#566]
^ title.
https://github.com/SpongePowered/SpongeDocs/blob/master/source/plugin/practices.rst#mixins

**Comment by Inscrutable** [comment]
Well, sort of. A plugin using mixins is a lot more like a _mod_ than a _plugin_, according to accepted terminology. The only example I can think of so far is the Nucleus mixin-plugin, and that's highly experimental. So, do you want to have a try at a more concise statement to replace the existing text?

**Comment by pie-flavor** [comment]
'Plugins can use mixins, though by that point they're better classified as mods.'

The real message in the linked page was not one of terminology, but simply that mixins couldn't be used by things that Sponge loads.
