### ISSUE TITLE
Unwieldy builder creation in example code

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeDocs#568]
This is present in both the pages for [Scheduler](https://docs.spongepowered.org/master/en/plugin/scheduler.html) and [PaginationService](https://docs.spongepowered.org/master/en/plugin/text/pagination.html). Their methods for obtaining a `Builder`  can be replaced with `PaginationList.builder()` and `Task.builder()` respectively.

**Comment by Inscrutable** [comment]
Do you think you could submit a PR with these changes?
