### ISSUE TITLE
SpongeForge set-up tutorial videos are now private

### ISSUE THREAD

**Issue by Meronat** [SpongePowered/SpongeDocs#577]
Sibomots seems to have made [all of his tutorial videos](https://www.youtube.com/playlist?list=PLGqUurDwlOGfmRM_UkAVR0xrvIi9B6BQN) private, so for now it would be best to remove the link from [the tutorials docs page](https://docs.spongepowered.org/stable/en/plugin/tutorials.html) and maybe the page entirely until some new tutorials show up.

**Comment by Inscrutable** [comment]
I see. I have no idea what's happening there. You might want to ping him via IRC and ask what's going on, he *did* make them for public consumption ...

**Comment by Meronat** [comment]
Yeah I will if I see him online. He seems to have been deleting his posts on the forums as well, so maybe he is looking for a fresh start? I'm not really sure.

**Comment by Inscrutable** [comment]
He's no longer in the _SpongePowered_ organisation, either. I have no idea what's going on.

**Comment by Meronat** [comment]
He seems to have reopened the videos to the public.

**Comment by Inscrutable** [comment]
I have made contact, and as you have observed, he has restored the videos.
