### ISSUE TITLE
Move Workspace Setup Information to a central page

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#58]
There are multiple pages explaining how to download and use the JDK, IDE, git, gradle, etc.

It's always the same procedure, for plugin development and API/Mod development.

I'm suggesting:

* Page about JDK installation
* Page about Gradle (download command line, alternative IDE plugins, brief tutorial)
* Page about git (download, command line, alternative IDE plugins, brief tutorial)
* Page about Eclipse (download, recommended plugins, first project tutorial)
* Page about IDEA (download, recommended plugins, first project tutorial)

We can keep the separate "Workspace Setup" pages for Plugin, Forge Mod and API development, and add links to the 5 suggested pages.

**Comment by BlackGoat** [comment]
Actually, Owexz and I have already been doing exactly that. There's a JRE guide in /users/java, a JDK guide in /plugins/javadevkit, and pages for IDEA, Eclipse and NetBeans in the /plugins foilder too. These are shared between the pages as needed. The Gradle and Eclipse pages haven't had much attention, if it's possible to do the same with them, go for it!

**Comment by boformer** [comment]
I just think that there should be another folder like "devs" and "plugins" for these pages, maybe named "workspace"

**Comment by boformer** [comment]
Or just name it "tools", all those things on my list are tools.

**Comment by BlackGoat** [comment]
That would make sense. It will be a complicated PR, moving a bunch of links on various pages. Have a stab at it if you like. I'm not sure where this fits in with "Git-Fu", though.

**Comment by tyrannokapi** [comment]
I am working on this, albeit in a slightly different fashion.
