### ISSUE TITLE
Custom Data code example link is dead

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#581]
The "full implementation" link on [this](https://docs.spongepowered.org/stable/en/plugin/data/custom/index.html) page is dead.

**Comment by Aaron1011** [comment]
This is waiting on https://github.com/SpongePowered/Cookbook/pull/17, so it's not really 'outdated'

**Comment by Inscrutable** [comment]
BUMP. This needs to come back to life soon, it's been a dead link for 4 months or so. Either that or we drop the link, as it's useless.

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/Cookbook/pull/17 was merged 16 hours ago.
