### ISSUE TITLE
Document requirements for displaying of block-owner and -notifier

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#584]
Just came across this issue and i feel we need to document that somewhere

What are the requirements to display the block-owner and block-notifier to someone using SF on the client? Currently it looks like you need a certain permission AND op on the server to see them on the *F3* debug screen.

Mostly a reminder for myself to investigate this and document it on the docs.

**Comment by ST-DDT** [comment]
👁 👁 
====

Maybe this is related to #747 .
Is there someone who knows anything about this? Otherwise I will look into this myself.
