### ISSUE TITLE
Document MCP version matching when using shaded jar with forgemods

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#585]
We need to document that mod developers which make use of our SF shaded jar, need to match the MCP mapping version of their mod to the MCP mapping version used by SF.

This does *only* apply to a mod workspace when SF shall be run inside it.

**Comment by ST-DDT** [comment]
@Tzky Can you give a little bit more context for this one?

AFAICT this is only relevant for the following pages:
* https://docs.spongepowered.org/stable/en/plugin/internals/mcp-setup.html
* https://docs.spongepowered.org/stable/en/plugin/debugging.html

A hint/note like this should probably be enough:

> Please note that running your plugin from the IDE requires that you use the same MCP mapping version as SpongeForge. You can check SpongeForge's mapping version like `X` and your own in your `build.gradle`. See also `<Using MCP in Your Plugin>`

Is this sufficient or did I miss some aspects of the issue?

**Comment by phit** [comment]
no, that should be enough

**Comment by ST-DDT** [comment]
Waiting for https://github.com/SpongePowered/SpongeForge/issues/2399 for an easy way to get the mapping version for the SpongeForge jar.

**Comment by Zidane** [comment]
Once SF and SV are built, this will now be in the MANIFEST.MF:

MCP-Mappings-Version: snapshot_20180808
