### ISSUE TITLE
Note that plugins with Mixins can only be loaded from the Mods folder

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeDocs#588]
Not sure if this restriction is implied on SpongeVanilla however SpongeForge (as per SpongePowered/SpongeForge#1339) cannot load plugin mixins outside the mods folder.

**Comment by Mumfrey** [comment]
Corollary to #566 and the corresponding #572.

**Comment by Inscrutable** [comment]
We probably also need to modify [this page](https://docs.spongepowered.org/stable/en/server/management/plugins.html). The note should be altered to mention that plugins can also reside in the ``plugins`` folder, and add the caveat above.

**Comment by Tzky** [comment]
Fixed in 000a1ad988858ea608428ef1c859aeb9a14cc7c8.
