### ISSUE TITLE
Permission and plugin id namings don't match

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeDocs#591]
The [permissions docs](https://docs.spongepowered.org/stable/en/plugin/permissions.html#permission) suggest using the plugin id as the 'root permisison node'. The example is `myPlugin`.
The [plugin id docs](https://docs.spongepowered.org/stable/en/plugin/plugin-identifier.html) say that plugin ids must be lowercase. And the example from the permission `myPlugin` isn't lowercase.

**Comment by Minecrell** [comment]
That sounds like something for https://github.com/SpongePowered/SpongeDocs/issues/437

**Comment by randombyte-developer** [comment]
Ok
