### ISSUE TITLE
SpongeForge installation page provides unclear link to correct Mojang launcher

### ISSUE THREAD

**Issue by LordRalex** [SpongePowered/SpongeDocs#592]
Currently on the SpongeForge installation steps, there is a warning that using the Minecraft Installer that Mojang provides only installs 8u25, and that Sponge requires 8u40.

It then links to the download page for Minecraft, which effectively links that same installer that causes the issue.

It should either link to an article that explains how to change the Java version for the installed version or link a page which is more clear about what to download.

I've planned on adding this java change as a CMS page on http://hopper.minecraft.net/help/ and will update this issue should it be useful to link to instead, as linking older versions isn't ideal to me.

Page which has the issue: https://github.com/SpongePowered/SpongeDocs/blob/stable/source/server/getting-started/implementations/spongeforge.rst#installing-spongeforge-1 (https://docs.spongepowered.org/stable/en/server/getting-started/implementations/spongeforge.html)

**Comment by Inscrutable** [comment]
It links to the Minecraft DL page because you can also grab the Launcher _without_ Java bundled with it. There is already a nice page on the SpongeDocs about [Installing Java](https://docs.spongepowered.org/stable/en/server/getting-started/jre.html), which we should just link here for convenience.

**Comment by Meronat** [comment]
@Inscrutable While we do mention that you can grab it there, it is not completely obvious as you do need to go to "alternative download" once there. Also while we do have the installing Java article already, it may be helpful to provide some information or link to an external guide on how to change the Java version within the newest Minecraft client if they did use the installer or want to change where the Java install is located or similar.

**Comment by MarkL4YG** [comment]
By the way...  
> The Java installers from the linked website should detect whether your computer is ready for 64-bit.  

*Links manual download page*

**Comment by ST-DDT** [comment]
* [x] Mention Sponge needs Java 8.0.40
* [ ] Link to how to install Java / config JRE
* [ ] Mention alternative download section
* [ ] Automatic download page
  * Can somebody  verify whether https://java.com/en/download/ will point to a link that actually to a proper x64 variant?

**Comment by LordRalex** [comment]
Java.com may not always point right. 

Firefox and Chrome pulled 64 bit for me, but IE 11 pulled a 32 bit, which when I did the install to, picked off the old Java 7 installed which is 32bit.
