### ISSUE TITLE
SpongeFoundation

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/SpongeDocs#595]
I was unsure if open a PR for this as there's no info on the forum (as far as I know), but the link to the SpongeFoundation website is dead https://github.com/SpongePowered/SpongeDocs/blob/stable/source/about/glossary.rst 

What happened to the website ? There's still the category on the forum https://forums.spongepowered.org/c/foundation

**Comment by ST-DDT** [comment]
I guess your are referring to this (http://spongefoundation.org/) page.
AFAICT the DNS has not changed for a while, so I guess the server is not (yet) properly setup.
@SpongePowered/web-developers @SpongePowered/webdevops

**Comment by Inscrutable** [comment]
The person who is supposed to know what's going on here is Dockter.

**Comment by lukegb** [comment]
I'm not sure the spongefoundation landing page ever got moved across (see also SpongePowered/Sysadmin#11). To be honest it both looked a bit naff and was filled with inaccurate information at the time, so I'm not sure it's a great loss - I think I do still have a copy of it on my desktop somewhere, but it's probably better off just making it a redirect to SpongeDocs somewhere or making it a part of the new SpongeHome.

I also got poked about the MX, which is currently set to `mail.mcsnetworks.org`, which doesn't resolve, but I never set that so I assume someone else did at some point and it changed.

**Comment by Meronat** [comment]
Yeah I agree the information would be best included in its own page on SpongeHome and have the URL redirect there. Consolidates the org into a single website.

**Comment by Inscrutable** [comment]
Has there been any progress on this? At present it just duplicates www.spongepowered.org. Or should we just remove mention of the Foundation and never speak of this again? ;)

**Comment by progwml6** [comment]
@mcsnetworks if you want this restored its probably going to need a new codebase as I have no clue where the old one ended up as i'm not seeing it on our github anywhere

**Comment by ImMorpheus** [comment]
I'm gonna close this as the link has been removed.
