### ISSUE TITLE
Known Mod Conflicts Page

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeDocs#598]
I've been thinking about this for a while, would it be worth it maintaining a page with known mod conflicts with their workarounds/replacements? Currently you have to search for that kind of information in the various issue trackers. I started an example here how this could look like https://github.com/phit/Sponge-ModSupport

Is this in the scope of the docs and worth maintaining or is the current approach of making people go through the issue tracker enough?

**Comment by Inscrutable** [comment]
It's out-of-scope for the SpongeDocs, but there's good reason to have such a list available. I have suggested we maintain one somewhere on the Forum, so it turns up in search results. The matter is still under debate - we don't want to have a "name-and-shame" list, just the basic facts and links to forks or patches where available.

**Comment by Inscrutable** [comment]
As no-one else has had anything significant to say, I'll close this issue. I think the concept is still quite a good one, but will need more discussion before anything goes ahead.
