### ISSUE TITLE
Server crashing when person leaves the server

### ISSUE THREAD

**Issue by Alexdenseje7** [SpongePowered/SpongeDocs#599]
Crash report:
https://pastebin.com/dduE9dFc

The server crashes when the someone leaves the server.

Newest version of sponge vanilla.

**Comment by Minecrell** [comment]
Please open this issue on one of the implementation repos:

- https://github.com/SpongePowered/SpongeVanilla/issues
- https://github.com/SpongePowered/SpongeCommon
