### ISSUE TITLE
Cause accepting plugin instance or plugin container?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#602]
I probably need someone to verify I didn't make a mistake, but I believe all the plugin instances on this page, need to be replaced with plugin containers instead.

https://docs.spongepowered.org/stable/en/plugin/blocks/modifying.html?highlight=modifying%20blocks

**Comment by Deamon5550** [comment]
Yeah they should be

**Comment by Inscrutable** [comment]
Which version of the API did this change in (so I can add the right milestone), or is it an error?

**Comment by ryantheleach** [comment]
I'm not sure if it was an intentional change or error in the docs, or an error in the implementation.
