### ISSUE TITLE
"Is are"

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeDocs#604]
Contents of title are in the second Notes section under the header Signing your Plugin on the [publishing&nbsp;page](https://github.com/SpongePowered/SpongeDocs/blob/stable/source/ore/publish.rst#signing-your-plugin).
```
 there is are plugins
```

**Comment by Inscrutable** [comment]
This probably fits better into #437, our ongoing OCD list for minor fixes. Oh well.

**Comment by Minecrell** [comment]
https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-307758372
