### ISSUE TITLE
document fetching the jar pgp signature

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/SpongeDocs#612]
on `https://docs.spongepowered.org/stable/en/ore/routes/download.html` it is mentioned that we can use `/api/projects/:pluginId/versions/:version/download` to download a plugin jar. 

It misses that we can use `/api/projects/:pluginId/versions/:version/signature` to get the pgp signature

**Comment by ryantheleach** [comment]
Thanks king, we would appreciate a PR :)
