### ISSUE TITLE
Document downloading the jar from a zip file

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/SpongeDocs#613]
I believe I once talked with windy about developers uploading zip files containing the jar + extra files, and that only downloading the jar and downloading the zip was possible. Not sure if thats possible now, but documentation is not present.

@windy can comment on that?

**Comment by ST-DDT** [comment]
Pinging @windy1 @SpongePowered/ore is there an option to only download the jar that was embedded inside an uploaded zip file? Is there a way to validate the signature of that jar? (How is the jar identified if there are more than one?)

IMO its most likely that neither is not possible.

Related docs page: [Ore - Web-API - Download Project Version](https://docs.spongepowered.org/stable/en/ore/routes/download.html)

Are there API docs / list of all possible API calls somewhere (excluding this repo)?

**Comment by ST-DDT** [comment]
@phase Can you comment on this one please?

**Comment by phase** [comment]
Only jars can be uploaded and having extra files with the jar isn't on the roadmap currently.
