### ISSUE TITLE
Addition of '/sponge:help' permission

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeDocs#619]
As of [this commit](https://github.com/SpongePowered/SpongeCommon/compare/2af6807b35d6...4e82a4ec9965) `/sponge:help` has the permission `sponge.commands.help` tied to it.

**Comment by Inscrutable** [comment]
Presuming this targets bleeding (API 7), will it get cherry-picked into older API versions?

**Comment by Grinch** [comment]
The only version I targeted for this is 7. It could be pulled into older versions but that isn't something I personally plan to PR.
