### ISSUE TITLE
Misleading information in plugin management section

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeDocs#630]
In <code><a href="https://github.com/SpongePowered/SpongeDocs/blob/stable/source/server/management/plugins.rst">plugins.rst</a></code>: 
> * Is the plugin compatible with your Minecraft version? While Sponge tries to keep old plugins working, this is sometimes not possible. In most cases, plugins based on a stable release should continue functioning without being updated.

Sponge is not hesitant to break plugins for a better API, as evidenced by the recent command changes, and plugins are prone to stop functioning without being updated, even if based on stable releases. This section would be better off being replaced with a user-friendly version of <code><a href="https://github.com/SpongePowered/SpongeDocs/blob/stable/source/contributing/versioning.rst#semver">versioning.rst#semver</a></code>.

**Comment by ryantheleach** [comment]
Sponge does make an effort to keep old plugins working. Just not at the expense of bad API.

**Comment by gabizou** [comment]
It does make an effort within the same major version. If we had kept the same API release for multiple Minecraft versions, we could support multiple Minecraft versions. In the current case, there are three supported API versions of which have their own Minecraft related version. We could link to semver for the sake of mentioning to plugin developers and server owners, but ultimately, the major API version is all that will matter for Minecraft version comparisons.

**Comment by pie-flavor** [comment]
@gabizou Yes, and it could be misleading for some; they could read the page and be under the impression that plugins are likely to work across a few major releases. I came across this when i was attempting to respond to a forum post about whether API 6 plugins would work in API 7, and found that there wasn't any (user-intended) documentation to link to.

**Comment by Inscrutable** [comment]
A caveat could be added about experimental/bleeding builds, as that's where most of the big breakage has been. But the best we can really offer is to suggest they try it and see, as changes made in the API don't always have a broad influence, and so may affect fewer plugins. Exactly what plugins break is determined by going into the nitty gritty of the API changes, and semver is a crude approximation of that. You can always write some user-facing blurb about semver that suits the purpose and offer it as a PR, but beware of bloat.
