### ISSUE TITLE
Document login permissions

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeDocs#641]
The permissions added by the following PR (is merged) should be documented somewhere:
https://github.com/SpongePowered/SpongeCommon/pull/1012

**Comment by ST-DDT** [comment]
This should probably added to 
* https://github.com/SpongePowered/SpongeDocs/blob/stable/source/server/management/whitelist.rst
* and https://github.com/SpongePowered/SpongeDocs/blob/stable/source/server/spongineer/commands.rst

And while we are at it:
* https://github.com/SpongePowered/SpongeDocs/blob/stable/source/server/management/permissions.rst
* and https://github.com/SpongePowered/SpongeDocs/blob/stable/source/server/spongineer/commands.rst

should contain a link to
* https://github.com/SpongePowered/SpongeDocs/blob/stable/source/plugin/permissions.rst

and vice versa
