### ISSUE TITLE
Outdated references on Event Causes page.

### ISSUE THREAD

**Issue by LazoYoung** [SpongePowered/SpongeDocs#651]
[This part](https://docs.spongepowered.org/stable/en/plugin/event/causes.html#named-causes) describes how to retrieve named objects in cause chain.

```java
@Listener
public void onGrow(ChangeBlockEvent.Grow event) {
    Optional<Player> notifier = event.getCause().get(NamedCause.NOTIFIER, Player.class);
}
```

The sample code refers to `Cause#get(String, Class)` and `NamedCause`  which don't exist in the current javadoc for SpongeAPI. I guess those were replaced by EventContext since [the refactor on event causes](https://github.com/SpongePowered/SpongeAPI/issues/1184)

**Comment by ST-DDT** [comment]
Probably related : https://github.com/SpongePowered/SpongeDocs/issues/640

**Comment by LazoYoung** [comment]
Document also needs to provide the usage for EventContext, replacing the old NamedCause examples.
