### ISSUE TITLE
Outdated references Ray Tracing

### ISSUE THREAD

**Issue by The-Defman** [SpongePowered/SpongeDocs#653]
Pull request #655 

maxDistanceFilter is no longer present at Sponge API7
filter have been replaced with skipFilter and stopFilter

Suggested changes is as followed

```java
BlockRay<World> blockRay = BlockRay.from(player)
    .filter(BlockRay.continueAfterFilter(BlockRay.onlyAirFilter(), 1)).build();
```

to

```java
BlockRay<World> blockRay = BlockRay.from(player)
    .stopFilter(BlockRay.continueAfterFilter(BlockRay.onlyAirFilter(), 1)).build();
```

and the Predicate ``BlockRay.maxDistance``have been removed entirely.
* ``maxDistanceFilter(Vector3d, double)``: returns a filter that stops at certain distance from the given Vector3d

https://github.com/SpongePowered/SpongeDocs/blob/stable/source/plugin/ray-tracing.rst

As a final comment; this is my first issue, please don't be to hard on me.

**Comment by ryantheleach** [comment]
Hey @The-Defman Reviewing this change, I'd recommend that people use the BlockRay Builder's distanceLimit() option.

`     public BlockRayBuilder<E> distanceLimit(double distanceLimit)`

This simplifies the maxDistanceFilter somewhat by removing the extra Vector3d as most people wanted to measure the distance from the origin anyway, In addition I can't find maxDistanceFilter in the API? Can you link to where it is in stable-7? Thanks.

**Comment by The-Defman** [comment]
What I tried to write is that maxDistanceFilter have been removed and the documentation should reflect the use of ``distanceLimit(double distanceLimit)`` instead.

**Comment by Inscrutable** [comment]
I'd be delighted if you bundle these suggested changes into a Pull Request that we can beat into shape. It's easier to discuss that way, and others can contribute to finalise it.

**Comment by The-Defman** [comment]
I have now created a pull request at #655. This is my first pull request and feedback will be loved. As a final note I'm not a native speaker and therefor the spelling might be slightly off.
