### ISSUE TITLE
License page uses 3 columns instead of paragraphs

### ISSUE THREAD

**Issue by LordRalex** [SpongePowered/SpongeDocs#664]
https://docs.spongepowered.org/stable/en/about/license.html

The page currently shows each paragraph in a vertical column, this makes reading this page nearly impossible as they are paragraphs.

The page should follow how other pages go and read downward.

**Comment by Inscrutable** [comment]
I saw this last night too. It's downright weird, as that page hasn't changed since early last year. This will need some investigation, as the original looks normal to me. Something in our post-processing has messed this up somehow.
