### ISSUE TITLE
Mistype in "List Users" section of Ore Web API

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/SpongeDocs#665]
![image](https://user-images.githubusercontent.com/9044780/36349029-c2e9a054-1442-11e8-97c2-0aca6db41b1a.png)

**Comment by parlough** [comment]
@progwml6 What is the actual format of the createdAt? I'm assuming the second entry(gabizou's) is supposed to be like Zidane's?

**Comment by ST-DDT** [comment]
Refers to this page: https://docs.spongepowered.org/stable/en/ore/routes/list-users.html

-----------------

Slightly offtopic but have we documented the base url for the Ore API somewhere? I couldn't find it.

**Comment by ItsDoot** [comment]
@ST-DDT Pretty sure it's just https://ore.spongepowered.org

**Comment by felixoi** [comment]
The base url is https://ore.spongepowered.org/api

**Comment by ST-DDT** [comment]
If I/we fix this issue we should probably also update the examples, as there might be new values in there.

**Comment by ST-DDT** [comment]
Apparently this got fixed in https://github.com/SpongePowered/SpongeDocs/commit/e02b2d6bf12ab9413fabac5f4d18eda10ce6ac46
