### ISSUE TITLE
Logging changes

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeDocs#673]
SpongeDocs will need to be updated to reflect the logging changes in Forge 1.12, mainly opening an issue here as an reminder for myself.
This is already outdated even without the other stuff I'm gonna link here
https://docs.spongepowered.org/stable/en/server/spongineer/logs.html#spongeforge-logfiles
as the only useful log file in 1.12 was fml-junk, which was now removed

https://github.com/mezz/MinecraftForge/blob/ef7f1af097ba11eebb998323d2b10948486dee96/SUPPORT.md#identifying-the-source-of-a-problem

the new log files are `latest.log` and `debug.log`

I'm gonna wait with a PR for this until compat for these changes has been solved for SpongeForge https://github.com/SpongePowered/SpongeForge/issues/2054

**Comment by Inscrutable** [comment]
The linked issue was closed; is this still a problem @phit ?

**Comment by phit** [comment]
the bugs are mostly fixed, but yes the docs still need to be updated
