### ISSUE TITLE
Add note to Plugin Mixins that the jar file has to be placed in the mods folder for SpongeForge

### ISSUE THREAD

**Issue by nihiluis** [SpongePowered/SpongeDocs#675]
I made the mistake to place my mixin jar file into the mods/plugins directory while using SpongeForge. It has to be placed into the mods folder though. I think a note might save someone like me some time in the future.

**Comment by Inscrutable** [comment]
There is **already** a note in https://docs.spongepowered.org/stable/en/server/management/plugins.html to this effect. ``Please note that plugins which make use of Mixins must reside inside the mods folder.``

**Comment by nihiluis** [comment]
So? I was reading this when I first started Sponge with no interest to Mixins whatsoever. Then I became interested in Mixins and of course didn't read the Installing Plugins again.

Do you think everyone studies the documentation and then is done with it for ever?
Or from another point: Why would I return to that page? What's your supposed reason? 

And why do you think it would be unfitting to have that piece of information there too? I mean just because there is one sentence at the beginning of a documentation, doesn't mean related and important information can't be located where it actually matters and where a sane person would look into.

Really unable to comprehend this. Please explain your response.

**Comment by phit** [comment]
where would you like the note to be besides under installing plugins? that seems most relevant

**Comment by nihiluis** [comment]
Maybe right at the bottom of the page at https://docs.spongepowered.org/stable/en/plugin/internals/mixins.html
and continue the list with i.e.

```
5. If you're using SpongeForge make sure to put the resulting jar into the mods directory and not the mods/plugins directory.
```

not perfect, but ok imo.
