### ISSUE TITLE
Entities in every dimension except spawn world invincible

### ISSUE THREAD

**Issue by DragaoNimhe** [SpongePowered/SpongeDocs#676]
Hey there, I looked through all open issues and was unable to find another similar to mine, I apologize if this has been brought up already. I'm a developer for the Mech and Magic modpack on ATLauncher, and we're getting ready to launch a server for the pack. We are running into a major issue, however; all entities that are not in the initial spawn world will not drop in hearts or die when attacked. They appear to "die" repeatedly, as in they drop loot as if they have died every couple of hits, but do not actually die. We are able to damage mobs normally within the "main" world, but not in any other dimension. We are currently running the latest version of sponge forge 1.12.2-7.1.0 (beta-2990) but this problem persists on every version of 1.12.2-7.1.0 that we have tried. The main developer for the pack is also hosting a server, and he is having the exact same issue.

When a mob is attacked, it does not cause any errors or logs to occur in console or the files.  We have loaded the server without any plugins at all and the issue still persists, so it's not due to a plugin we are using. I can post any further information you require, and any help with this issue would be greatly appreciated.

**Comment by CathalCraft** [comment]
Same exact issue on my server as well with the Sponge Forge 1.12.2-7.1.0 builds. It's very annoying and I'm glad to hear I'm not the only one so this could be resolved.

**Comment by phit** [comment]
Please post this on the [SpongeForge](https://github.com/SpongePowered/SpongeForge/issues) issues tracker, this here is to track documentation issues for the Sponge [Documenation](https://docs.spongepowered.org/). Not bugs, crashes etc.
https://github.com/SpongePowered/SpongeForge/issues

make sure to fill out the provided issue template, thanks!

**Comment by Inscrutable** [comment]
Hi folks. We appreciate your well-formulated bug reports very much!

However, this is the *SpongeDocs* repository, so all we can do is write about it. You might want to put this issue in the [*SpongeForge* repo](https://github.com/SpongePowered/SpongeForge), where they can make better use of the info.

PS: Don't forget to include the version(s) of Forge used, and a list of the mods would be great.
