### ISSUE TITLE
Reorder sections to make it easier for noobs

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/SpongeDocs#684]
Some sections in plugin creation could do with reordering so it is easier for noobs like me to read it as we begin coding.

Sections noticed so far with a recommended order of placement:
Basic Listener Info > Config Basics + Guide > Complex Config Info

**Comment by afriestad** [comment]
I would also recommend moving "Text" in between "Logging and Debugging" and "Commands", as Commands has a note that recommends reading the Text docs first.
