### ISSUE TITLE
Usage-example of PermissionDescription not up to date

### ISSUE THREAD

**Issue by MinusKube** [SpongePowered/SpongeDocs#710]
The usage-example of PermissionDescription [here](https://docs.spongepowered.org/stable/en/plugin/permissions.html#usage-example) is not up to date, since 7.0.0, the `newDescriptionBuilder` [doesn't return an Optional anymore](https://jd.spongepowered.org/7.0.0/org/spongepowered/api/service/permission/PermissionService.html#newDescriptionBuilder-java.lang.Object-), and so, this part should be updated.

**Comment by Inscrutable** [comment]
Many of the code examples in the docs are out of date. @parlough was working on a PR (#691) to update them and amend licensing, I'm not sure how progress is on that.

**Comment by ST-DDT** [comment]
All Java examples which are declared as such have been checked recently for compiling with the latest api version.
In this case it has been declared as text and thus was missed.
