### ISSUE TITLE
Mark old-release Ore guidelines as outdated

### ISSUE THREAD

**Issue by mbax** [SpongePowered/SpongeDocs#719]
Could the older guidelines (I believe just 6.0.0 and 5.1.0 at present) be updated to indicate they are not the present version of the docs, and link to the latest (stable?)? Some sort of message at the top of the page, I would propose.

**Comment by Inscrutable** [comment]
If we're going to do this, we should do something similar with the rather more critical pages of Rules, (and eventually TOS, Privacy Policy too). Anything we depend on for licensing, terms and rules needs to point to the latest version as definitive.

**Comment by dualspiral** [comment]
Is there a way to store these pages outside of the API versioning system? I suspect not, but that would be the ideal solution...

**Comment by Inscrutable** [comment]
Not that I know of. It would be harder to offer translations too, as it would complicate things with the way we send stuff to Crowdin. It's probably better to just make sure it's clear that the definitive version of our Rules, policies etc should always be found in the latest version.

**Comment by ST-DDT** [comment]
I will add it to those pages as well.
Can someone search for all relevant pages? I will look myself later on, but I dont want to miss one.

**Comment by ST-DDT** [comment]
Lets move the discussion to the PR, otherwise we have two places for discussions.
