### ISSUE TITLE
Action to translate redirect on bad URL

### ISSUE THREAD

**Issue by RedRelay** [SpongePowered/SpongeDocs#721]
By contributing in translating when unlogged from crowdin, we are redirect into a bad URL after login (at least using github oauth).

Example :
https://docs.spongepowered.org/stable/translate/plugin/data/serialization.html -> https//docs.spongepowered.org/stable/translate/plugin/data/serialization.html 

(missing `:` after protocol)

**Comment by Inscrutable** [comment]
On what page(s) does this broken redirect linkage appear? It's not something directly in the docs, so I suspect something in our meta systems needs tweaking.

**Comment by RedRelay** [comment]
I can't reproduce, maybe it is fixed
