### ISSUE TITLE
commands page missing selector permission node

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeDocs#722]
apparently its a thing added years ago 

https://github.com/SpongePowered/SpongeCommon/blob/a9423c7ec9f2b423b52c273f7e7a23818a8f3e41/src/main/java/org/spongepowered/common/command/CommandPermissions.java#L46

https://github.com/SpongePowered/SpongeCommon/pull/940

but its not mentioned on the commands page https://docs.spongepowered.org/stable/en/server/spongineer/commands.html

**Comment by ST-DDT** [comment]
Any suggestion where to add this?
Maybe after the commandblock and bypass permission list?

**Comment by phit** [comment]
probably above the vanilla table, as some of the vanilla commands use selectors

**Comment by ST-DDT** [comment]
It looks like there are also other details missing. See: https://github.com/SpongePowered/SpongeDocs/issues/618#issuecomment-407265651

**Comment by ST-DDT** [comment]
I might tackle this along with #618 . See other issue.

**Comment by ST-DDT** [comment]
Note to self: The following permissions are missing from the docs:

* minecraft.selector
* sponge.debug.block-tracking
* sponge.debug.hover-stacktrace
* sponge.command.blockinfo
* sponge.command.entityinfo
* sponge.command.which
