### ISSUE TITLE
Mentioned BungeeCord Issues have been closed

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeDocs#748]
[Docs: `bungeecord.html`](https://docs.spongepowered.org/stable/en/server/getting-started/bungeecord.html?highlight=Pull%20requests#ip-forwarding) | [Source: `bungeecord.rst`](https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/getting-started/bungeecord.rst#L39)

> For SpongeVanilla or Vanilla clients connecting to unmodded SpongeForge, IP Forwarding works out of the box. [Pull](https://github.com/SpigotMC/BungeeCord/pull/1557) [requests](https://github.com/SpigotMC/BungeeCord/pull/1678) have been supplied to BungeeCord to allow BungeeCord to support SpongeForge natively. We are awaiting it to be included in the main product. For now please use one of the solutions mentioned above.

The linked issues have been closed, so we cannot keep the as "awaited". We should probably either update the references to their successor or rephrase it like: `These contributions have been rejected, so you don't have any other choice than use one of the solutions mentioned above.`

Asking @dualspiral for insider knowledge.

**Comment by phit** [comment]
oh I thought i got rid of the awaiting part, guess not 
https://github.com/SpongePowered/SpongeDocs/pull/682/files#diff-776381a885489b6feb00ba1961494247L36

though really we are still waiting for it to maybe get supported some day by mainline BungeeCord

**Comment by ST-DDT** [comment]
If we are still waiting, then I guess the docs are valid as it. Closing.

**Comment by dualspiral** [comment]
Honestly, I’m tired of waiting. It’s not going to happen, realistically. With Waterfall and Hexacord supporting our protocol changes and Velocity on its way, I think we can (and should) remove those statements and suggest the alternatives instead.

**Comment by ST-DDT** [comment]
Would the following change be appropriate?

From

> For SpongeVanilla or Vanilla clients connecting to unmodded SpongeForge, IP Forwarding works out of the box. [Pull](https://github.com/SpigotMC/BungeeCord/pull/1557) [requests](https://github.com/SpigotMC/BungeeCord/pull/1678) have been supplied to BungeeCord to allow BungeeCord to support SpongeForge natively. We are awaiting it to be included in the main product. For now please use one of the solutions mentioned above.

To 

> For SpongeVanilla or Vanilla clients connecting to unmodded SpongeForge, IP Forwarding works out of the box. Sponge supplied fixes to BungeeCord for modded SpongeForge support, but these haven't been merged since. So use one of the solutions mentioned above.

**Comment by phit** [comment]
I'd go with this, doesn't hurt to link our attempts.
> For SpongeVanilla or Vanilla clients connecting to unmodded SpongeForge, IP Forwarding works out of the box. Sponge supplied [fix](https://github.com/SpigotMC/BungeeCord/pull/1557)[es](https://github.com/SpigotMC/BungeeCord/pull/1678)  to BungeeCord for modded SpongeForge support, but these haven't been merged. Please use one of the solutions mentioned above.
