### ISSUE TITLE
Plugin mixins setup is failing

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/SpongeDocs#752]
https://github.com/SpongePowered/SpongeDocs/blob/ff0f5b9f1664046e2a3549024b88c8026b77228a/source/plugin/internals/mixins.rst#L96

should be `ext.refMap = "mixins.myplugin.refmap.json" `

See https://github.com/SpongePowered/MixinGradle/issues/3

**Comment by ST-DDT** [comment]
AFAICT the current documentation was correct at some point, wasn't it? Is there also a change in the version numbers we have to include?

**Comment by ImMorpheus** [comment]
I'm using mixin 0.7.11-SNAPSHOT and gradle 4.4.1. 

The wiki is using 'org.spongepowered:mixin:0.7.5-SNAPSHOT' but I haven't tested that version.

**Comment by gabizou** [comment]
It was correct back when gradle 2.x was still the latest thing, I think up until gradle 3.4 or around there. Now we're on to gradle 4.9 where the `ext.refMap` is required.
