### ISSUE TITLE
Server commands page out of date

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeDocs#772]
According to DrZoddiak on Discord:

The section 

> Since no dimension was specified, the dimension would default to the sender(player) dimension. So, if you were in a mystcraft dimension, this would alter the mystcraft dimension config.

is wrong.

![Pic-Docs](https://gyazo.com/3951885a3d536a9cd2bc0bd0f3a153b0.png)
![Pic-Error](https://i.gyazo.com/e89e5969579f9b6ab2e06aaa2409b003.png)

[commands-Docs](https://docs.spongepowered.org/stable/en/server/spongineer/commands.html?highlight=examples#sponge)

I can reproduce this behavior.

According to phit this behavior change from the server is intentional and just hasn't been documented in  the docs.

------------------------------------------

Aside from fixing this issue we should also check all other in-game commands whether they still work as mentioned.

**Comment by phit** [comment]
I touched a lot of this here https://github.com/SpongePowered/SpongeDocs/pull/714/files#diff-e6c62d5ada684044625780ea9a656f9fL55
