### ISSUE TITLE
Random Crashes with FTB Revelations 2.7.0

### ISSUE THREAD

**Issue by DeaSTL** [SpongePowered/SpongeDocs#781]
https://gist.github.com/DeaSTL/3902719c5f9a3c1ba979c0af5454684d

**Comment by DeaSTL** [comment]
I should mention that I removed foam fix because of a random crash on start up after adding sponge.

**Comment by phit** [comment]
SpongeDocs is the repo for our documentation, SpongeForge issues go here https://github.com/SpongePowered/SpongeForge/issues

either way there's already an issue for that there https://github.com/SpongePowered/SpongeForge/issues/2405

disable async lighting in the sponge config file
