### ISSUE TITLE
Documenting system properties

### ISSUE THREAD

**Issue by LordRalex** [SpongePowered/SpongeDocs#796]
Per question by @gabizou :

Sponge has some properties that you can set on the commandline-level that can assist with debugging or other tasks. These tasks should be documented and explained so advanced users can set them if needed.

I personally recommend this being a new page under the "Become an Expert Spongineer" as these settings are not for the average user. It's layout would probably be similar to the commands page, where it explains what values the setting expects and what it does.

These are all the classes in SpongeCommon which have a System.getProperty call. The calls in Forge and Vanilla are not added by sponge, and should probably not be included.

- [ ] https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/ListenerChecker.java
  - `sponge.shouldFireAll` (boolean, default false)
    Forces all boolean "performance" checks for common SpongeAPI events to be forcibly created and fired, regardless whether there is a registered event listener for the desired event (Sponge will normally not construct and throw a `ChangeBlockEvent` if there's no listeners for that event, or it's sub events).
  - `sponge.debugShouldFire` (boolean, default false)
    Logs changes to the `ShouldFire` flags when event listeners are registered/unregistered causing one of the boolean flags to be flipped (whether it's going from `true` to `false` etc.).
- [ ] https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/relocate/co/aikar/timings/SpongeTimingsFactory.java
  - `timings.bypassMax` (any value as long as it exists)
     Allows for bypassing the max number of frames to send to the Aikar's timing API. Setting this will not permit bypassing the limit unless the API is configured to permit it.
- [ ] https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/SpongeCauseStackManager.java
  - `sponge.debugcauseframes` (boolean, default false)
    Adds a StackTrace to each `StackFrame` for when either Sponge implementation, or a plugin, potentially corrupts the `CauseStackManager`'s `StackFrame`s, whether it's a frame being popped out of order, or popping an already popped frame. This is useful to find out where the frame was created.
- [ ] https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/tracking/context/SpongeProxyBlockAccess.java
  - `sponge.debugProxyChanges` (boolean, default false)
    Similar to the `StackFrame` exception creation, this tracks the stack trace for each `BlockTransaction` that is captured for a block being changed, neighbor notification request, or a `TileEntity` change. Useful to find out where each transaction is created, potentially adding more information if there is an exception thrown during the processing of said transactions. Should always be included for logs when reporting issues revolving these sort of transactions.
- [ ] https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/filter/FilterGenerator.java
  - `sponge.filter.debug` (boolean, default false)
    Writes out classes that are generated by the filter generator to the .sponge.debug.out folder, named after the class they are altering.
- [ ] https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java
  - `sponge.print_all_catalog_types` (boolean, default false)
    Prints out all registered `CatalogType`s and their `String` id's at the end of startup, useful for finding out what id's are registered from vanilla and mods and plugins for all created `CatalogType`s.
- [ ] https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/tracking/context/MultiBlockCaptureSupplier.java
  - `sponge.debugBlockTransactions` (boolean, default false)
    Prints out a very spam filled log for every block captured that is processed, including information about what `BlockState`s are proxied, what `BlockState`s exist on the `Chunk` during processing, and potentially what `BlockState`s existed prior to a future transaction changing positions. Likewise applies to tracking `TileEntity` instances. Useful for debugging purposes for the implementation, and potentially plugins, when dealing with `ChangeBlockEvent`s and their processing.

**Comment by gabizou** [comment]
Felt too lazy to make a proper reply, so I edited some comments into the OP with some explanations. I'll try to add some more explanation or clarifications if people need some for the tracking specific flags.

**Comment by LordRalex** [comment]
I removed the guice one from the list since it's not sponge-added. I did add a quick note about what the last 2 flags that weren't filled in did.

**Comment by Grauldon** [comment]
I started working on this today.

**Comment by Grauldon** [comment]
Docs [updated](https://github.com/SpongePowered/SpongeDocs/commit/a536bd3f01db09d3d5c300be25cf6e8e41c4e9d6) with the requested information.
