### ISSUE TITLE
Windows shell issue resolved, should be documented

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/SpongeDocs#797]
Through investigation with @Brycey92, on Windows 10, when Command Prompt or PowerShell is used to launch the server, every now and then the server will randomly hang with the only thing being logged is that the server skipped multiple seconds or minutes worth of ticks. This issue might also affect older Windows versions, but that is untested.

The problem was resolved by disabling `Quick Edit Mode` in the properties menu in either of the shells, and this should be properly documented in the Docs.

I suggest having a Warning for this in https://docs.spongepowered.org/stable/en/server/getting-started/launch-script.html

**Comment by Brycey92** [comment]
It's worth noting that this should be changed in the Defaults menu of the shells, which is the same as the Properties menu, but the changes are applied to all new instances.

**Comment by phit** [comment]
thats intended, when you mark something in quickedit it will freeze the process, that's been always the case and nothing related to sponge directly

https://stackoverflow.com/questions/30418886/how-and-why-does-quickedit-mode-in-command-prompt-freeze-applications

**Comment by Brycey92** [comment]
Of course it's intended and not related to sponge, but server admins should still know to turn it off to prevent accidentally marking things and freezing their servers.

**Comment by Grauldon** [comment]
Warning [added](https://github.com/SpongePowered/SpongeDocs/commit/280aa9dc2addc57e14d89e65687f03b44fb0704e) to suggested page.
