### ISSUE TITLE
Update configuration pages to use configurate

### ISSUE THREAD

**Issue by ZephireNZ** [SpongePowered/SpongeDocs#84]
The current configuration pages describe using Sponge's own ```ConfigFile```, which wraps around the typesafe API. This should be changed to instead use configurate's ```ConfigurationLoader```, which is what is now used.

I would update this myself, however I have little experience with either: I was just reading through the docs and noticed this.

**Comment by tyrannokapi** [comment]
I will look into this, thanks.

**Comment by DanielRHarris** [comment]
See #94
