### ISSUE TITLE
ContextCalculator docs state it must be thread safe, but use a potentially unsafe example

### ISSUE THREAD

**Issue by A248** [SpongePowered/SpongeDocs#845]
https://docs.spongepowered.org/stable/en/plugin/permissions.html#contexts

The ExampleCalculator becomes unsafe once `playerArenas` is modified. I think it is much more likely that users following the example will be modifying their HashMaps.

**Comment by A248** [comment]
@ST-DDT I am afraid that 07292b8f32aa66ea761525b8b27ea878a506eaa1 is not sufficient to make the example thread safe. The code is still vulnerable to race conditions in ways beside the mere use of a HashMap. For example:

```java
if (this.playerArenas.containsKey(uuid)) {
    accumulator.add(IN_ANY_ARENA);
    accumulator.add(new Context(ARENA_KEY, this.playerArenas.get(uuid))); // Possible NPE, Context enforces nonnull value
} else {
    accumulator.add(NOT_ANY_ARENA);
}
```

**Comment by ST-DDT** [comment]
Should be fixed now.

**Comment by A248** [comment]
Awesome
