### ISSUE TITLE
Tutorial how to share plugin source code on GitHub

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#85]
I think it would be good to have a step-by-step guide for "Open Source Plugin Development". This will motivate unexperienced plugin makersThe guide should be **simple** (one IDE, gradle-only, use GUI when possible):

1. Setup Workspace (JDK, IntelliJ [?], other tools - refer to other pages)
2. Create GitHub repo (License, README)
3. Clone repo
4. Setup Gradle project (build.gradle, dependencies - refer to other pages)
5. Write basic plugin (refer to other pages)
6. Commit, Push to GitHub
7. Debug plugin within IDE (refer to other pages)
8. Build plugin with gradle
9. Publish to Sponge plugin repo (include GitHub link in description, this should have its own page - refer to it)

**Advanced Stuff (maybe separate pages):**
* git command overview with use-cases and explaining graphics
* Explain GitHub pull requests, issues
* How to fork other plugins and send pull requests

**Comment by tyrannokapi** [comment]
I think a simple guide on using GitHub in plugin development may be justifiable, and potentially helpful for the people who are bound to ask for development help on the forums. Doing so would also encourage collaborative plugin development, which is a plus.

That said, I'm not sure if an advanced Git overview is within the scope of SpongeDocs. That starts getting outside the realm of Sponge. A simple overview on "setting up shop" on GitHub is probably okay, but I think we should link to an outside source for the more advanced stuff.

Have a hamburger. :hamburger:

**Comment by simon816** [comment]
There's no need to have much about Git and GitHub since they are both very well documented.
https://help.github.com/
http://git-scm.com/doc

Maybe a small introduction and a link to their docs is all that's needed.

**Comment by BlackGoat** [comment]
There is Git-Fu for Sponge development (https://docs.spongepowered.org/en/devs/git/index.html), so we can justify having something similar for Plugin Devs if needed.

**Comment by boformer** [comment]
I think this would be very useful. When I started using Maven and GitHub for my Bukkit plugins, there were no tutorials. It was hard to understand what Maven actually does, and how the Git commands work.

**Comment by Tzky** [comment]
@boformer 
Is this still an issue / a feature you'd like to see on the Docs?
We have instructions on how to setup the IDE with Gradle and afaik for debugging in the IDE too. I'm unsure if we should include the other mentioned topics, as there are several other guides on the web for this.

**Comment by boformer** [comment]
This would be a lot of work. I think it would be useful because the information is scattered on the internet.

I don't have the time to write the tutorial. I would just keep the issue open.

**Comment by Tzky** [comment]
A basic "how to Git(Hub)" guide was added to the docs. I'm not sure if the sourcecode sharing is a bit out of scope for the Docs ;)

**Comment by saladoc** [comment]
It is. If this is to be included in the docs at some point, it will be in the form of "User xy has posted an excellent guide on the forums".

I'd probably close the issue and once we actually finished documenting Sponge we may think about it again. Its usefulness is undoubted, yet while a very basic overview over the git-fu required for contributing was already debatable, this definitly is out of scope.

**Comment by Inscrutable** [comment]
Agreed. If someone offers us a nice PR at a later date we may consider it, but it's so low in the priorities that it's unlikely to get staff attention for a *long* time (it's already almost a year old). Closed for now.
