### ISSUE TITLE
Tracks?

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/SpongeDocs#86]
To be honest, while tracks are pretty neat, I find them to be a bit convoluted and hard to follow.  It's unlikely that most documentation readers will be patient enough to read through all of the tracks. I suggest looking at the structure of the [django documentation](https://docs.djangoproject.com/en/1.7/). It's simply split up into sections of content that is similar, as well as a tutorial at the beginning. I propose to move to a structure similar to this(potentially for end users as well?)

**Comment by BlackGoat** [comment]
Tracks are a way of minimising duplication. We'd have to expand and partially reproduce the pages to eliminate them. I fear that if we did so, readers would think "haven't I read this bit before?" at some point. I'd like to get a user's perspective on the current format. A mock-up (or at least a flowchart) of your proposed alternative would be helpful, my old brain has difficulty envisaging it.

**Comment by ryantheleach** [comment]
It's been a few commits since I last re-read the docs. Where are the tracks listed?

**Comment by tyrannokapi** [comment]
If I understand correctly, is this the structure you are proposing?

https://docs.google.com/document/d/1KGK9PGGmHFLTz3dEmBYZTkoAVE5uH5IMckpJ7rn3JUI/edit?usp=sharing

That's not a difficult restructuring, but it is one that I think we need more input on. Although the current structure doesn't really "flow" in terms of user experience, I don't think it's difficult to figure out... though, the links at the bottom of tracks could use more distinction between them.

Your proposal is cleaner, but the problem of repeated information still comes up with the IDEs. 

@ryantheleach Tracks are here: https://docs.spongepowered.org/en/latest/workspace/getting-started/

**Comment by gratimax** [comment]
@tyrannokapi I created a version of the document here https://docs.google.com/document/d/1JnOHap8-4DfTBKBvWW-zqp-HL0Ky3_dq3E0E0J863ZE/edit?usp=sharing in the Sponge drive folder, but you can still edit it. I am going to do some changes.

**Comment by tyrannokapi** [comment]
Alright.

How would restructuring the Docs affect the Transifex instance? I don't know much about how Transifex works, admittedly.

**Comment by gratimax** [comment]
@tyrannokapi Transifex will try to keep as many translation strings as it can, meaning if files are moved without modification the associated translations are also transferred. At least, this is how it has behaved in my testing.

**Comment by BlackGoat** [comment]
Not quite necroposting: does our new translation setup via CrowdIn function in a similar fashion?
Is this re-restructure plan still a going concern?

**Comment by tyrannokapi** [comment]
From what I can see, yes, the translation setup with CrowdIn appears to be functionally similar to the one we had with Transifex.

Restructuring the docs is likely still a concern. I will probably be able to work on restructuring the docs according to the proposed outline by the end of the week.

On a related note: the docs would benefit from having introductory text (overviews) for each section, to help readers understand what they are looking at and what the next step is. At the moment, readers are greeted by a page full of links for each section... which probably isn't ideal if we want the docs to be easy to follow.

**Comment by BlackGoat** [comment]
Thanks. Slightly Off-Topic, some intro text was recently added to most of the index pages. It's not just links any more, but could probably still be improved for easier navigation. Beware of bloat.
