### ISSUE TITLE
Table width unconstrained on RtD

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#87]
Tables look terrible on the Read-the-Docs pages (ie. http://sponge.readthedocs.org/en/latest/users/server-properties/ ). Something is wrong with the wrapping on the last column, that does not happen on the GitHub view. Can we fix this with Sphinx or RtD style settings?

**Comment by tyrannokapi** [comment]
After messing with the table in Inspect Element, this seems to fix the issue:

``.wy-table-responsive td, .wy-table-responsive th { white-space: normal; }``


Once I get home, I can make a PR to fix it - unless someone else wants to do it, as it's a relatively simple fix.
