### ISSUE TITLE
Add new Sponge commands

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#89]
A recent commit to Sponge added some new commands. These should be added to our page at source/users/commands. There's some sexy documentation with the commit at https://github.com/SpongePowered/Sponge/commit/be08be04b06b413686c7f6c574bf89e918e1d6d3
This issue shouldn't take long to deal with. Any takers?

**Comment by 12AwsomeMan34** [comment]
I'll tackle this on.
