### ISSUE TITLE
Example sponge.conf needed

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#9]
We need an example sponge.conf file and an explanation of its properties for the page /users/conf

**Comment by BlackGoat** [comment]
This file is now at server/getting-started/configuration/sponge-conf and needs more love. Surely there has to be more to sponge.conf than sql settings.

**Comment by ryantheleach** [comment]
https://gist.github.com/ryantheleach/f3d5271cff789f910493 contains the current files for the default sponge configuration as of build sponge-1.8-1371-2.1DEV-476

**Comment by BlackGoat** [comment]
Thanks. The global.conf is probably the best example we can use (or maybe world.conf), rather than all of them, and the file itself is also mostly self-explanatory, with embedded comments. There is no more "sponge.conf" file that I can see, so the sponge-conf page seems to be largely redundant and can be re-purposed for this. ... Are there still sql settings anywhere?

**Comment by ryantheleach** [comment]
Sorry I missed this, No I can't see SQL settings anywhere.

**Comment by BlackGoat** [comment]
No, the new conf files have no SQL options (as default, anyway). I edited them away.
