### ISSUE TITLE
Switch to using crowdin

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/SpongeDocs#97]
So transifex is a bit of a bummer when it comes to uploading/downloading stuff. It's pretty slow, and I have also had to fork the client in order to get it to do what I want(not very appealing). We are trying out using [crowdin](https://crowdin.com/project/spongetest/settings#reports-activity), which boasts more features and an overall nicer GUI. It is also the system used by Minecraft for their translations.

Interested for input from contributors and translators.

**Comment by boformer** [comment]
Looks alright. Just tried crowdin with the demo project: https://crowdin.com/translate/demo/

**Comment by gratimax** [comment]
We've pretty much switched already based on response to the [forum post](https://forums.spongepowered.org/t/switch-to-using-crowdin/5971), so closing.
